apiVersion: loadbalancer.cloudflare.m.cloudflare.com/v1alpha1
kind: LoadBalancerPool
metadata:
  annotations:
    meta.upbound.io/example-id: loadbalancer/v1alpha1/loadbalancerpool
  labels:
    testing.upbound.io/example-name: example_load_balancer_pool
  name: example-load-balancer-pool
  namespace: crossplane-system
spec:
  forProvider:
    accountIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    description: Primary data center - Provider XYZ
    enabled: false
    latitude: 0
    loadShedding:
      defaultPercent: 0
      defaultPolicy: random
      sessionPercent: 0
      sessionPolicy: hash
    longitude: 0
    minimumOrigins: 0
    monitorGroup: monitor_group
    monitorSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: primary-dc-1
    notificationEmail: someone@example.com,sometwo@example.com
    notificationFilter:
      origin:
        disable: true
        healthy: true
      pool:
        disable: true
        healthy: false
    originSteering:
      policy: random
    origins:
    - address: 0.0.0.0
      enabled: true
      header:
        host:
        - example.com
      name: app-server-1
      port: 0
      virtualNetworkId: a5624d4e-044a-4ff0-b3e1-e2465353d4b4
      weight: 0.6
