//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIRoutingInitParameters) DeepCopyInto(out *APIRoutingInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIRoutingInitParameters.
func (in *APIRoutingInitParameters) DeepCopy() *APIRoutingInitParameters {
	if in == nil {
		return nil
	}
	out := new(APIRoutingInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIRoutingObservation) DeepCopyInto(out *APIRoutingObservation) {
	*out = *in
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = new(string)
		**out = **in
	}
	if in.Route != nil {
		in, out := &in.Route, &out.Route
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIRoutingObservation.
func (in *APIRoutingObservation) DeepCopy() *APIRoutingObservation {
	if in == nil {
		return nil
	}
	out := new(APIRoutingObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIRoutingParameters) DeepCopyInto(out *APIRoutingParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIRoutingParameters.
func (in *APIRoutingParameters) DeepCopy() *APIRoutingParameters {
	if in == nil {
		return nil
	}
	out := new(APIRoutingParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIShield) DeepCopyInto(out *APIShield) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIShield.
func (in *APIShield) DeepCopy() *APIShield {
	if in == nil {
		return nil
	}
	out := new(APIShield)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *APIShield) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIShieldInitParameters) DeepCopyInto(out *APIShieldInitParameters) {
	*out = *in
	if in.AuthIDCharacteristics != nil {
		in, out := &in.AuthIDCharacteristics, &out.AuthIDCharacteristics
		*out = make([]AuthIDCharacteristicsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ZoneID != nil {
		in, out := &in.ZoneID, &out.ZoneID
		*out = new(string)
		**out = **in
	}
	if in.ZoneIDRef != nil {
		in, out := &in.ZoneIDRef, &out.ZoneIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ZoneIDSelector != nil {
		in, out := &in.ZoneIDSelector, &out.ZoneIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIShieldInitParameters.
func (in *APIShieldInitParameters) DeepCopy() *APIShieldInitParameters {
	if in == nil {
		return nil
	}
	out := new(APIShieldInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIShieldList) DeepCopyInto(out *APIShieldList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]APIShield, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIShieldList.
func (in *APIShieldList) DeepCopy() *APIShieldList {
	if in == nil {
		return nil
	}
	out := new(APIShieldList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *APIShieldList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIShieldObservation) DeepCopyInto(out *APIShieldObservation) {
	*out = *in
	if in.AuthIDCharacteristics != nil {
		in, out := &in.AuthIDCharacteristics, &out.AuthIDCharacteristics
		*out = make([]AuthIDCharacteristicsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.ZoneID != nil {
		in, out := &in.ZoneID, &out.ZoneID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIShieldObservation.
func (in *APIShieldObservation) DeepCopy() *APIShieldObservation {
	if in == nil {
		return nil
	}
	out := new(APIShieldObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIShieldOperation) DeepCopyInto(out *APIShieldOperation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIShieldOperation.
func (in *APIShieldOperation) DeepCopy() *APIShieldOperation {
	if in == nil {
		return nil
	}
	out := new(APIShieldOperation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *APIShieldOperation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIShieldOperationInitParameters) DeepCopyInto(out *APIShieldOperationInitParameters) {
	*out = *in
	if in.Endpoint != nil {
		in, out := &in.Endpoint, &out.Endpoint
		*out = new(string)
		**out = **in
	}
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = new(string)
		**out = **in
	}
	if in.Method != nil {
		in, out := &in.Method, &out.Method
		*out = new(string)
		**out = **in
	}
	if in.ZoneID != nil {
		in, out := &in.ZoneID, &out.ZoneID
		*out = new(string)
		**out = **in
	}
	if in.ZoneIDRef != nil {
		in, out := &in.ZoneIDRef, &out.ZoneIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ZoneIDSelector != nil {
		in, out := &in.ZoneIDSelector, &out.ZoneIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIShieldOperationInitParameters.
func (in *APIShieldOperationInitParameters) DeepCopy() *APIShieldOperationInitParameters {
	if in == nil {
		return nil
	}
	out := new(APIShieldOperationInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIShieldOperationList) DeepCopyInto(out *APIShieldOperationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]APIShieldOperation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIShieldOperationList.
func (in *APIShieldOperationList) DeepCopy() *APIShieldOperationList {
	if in == nil {
		return nil
	}
	out := new(APIShieldOperationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *APIShieldOperationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIShieldOperationObservation) DeepCopyInto(out *APIShieldOperationObservation) {
	*out = *in
	if in.Endpoint != nil {
		in, out := &in.Endpoint, &out.Endpoint
		*out = new(string)
		**out = **in
	}
	if in.Features != nil {
		in, out := &in.Features, &out.Features
		*out = new(FeaturesObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = new(string)
		**out = **in
	}
	if in.Method != nil {
		in, out := &in.Method, &out.Method
		*out = new(string)
		**out = **in
	}
	if in.OperationID != nil {
		in, out := &in.OperationID, &out.OperationID
		*out = new(string)
		**out = **in
	}
	if in.ZoneID != nil {
		in, out := &in.ZoneID, &out.ZoneID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIShieldOperationObservation.
func (in *APIShieldOperationObservation) DeepCopy() *APIShieldOperationObservation {
	if in == nil {
		return nil
	}
	out := new(APIShieldOperationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIShieldOperationParameters) DeepCopyInto(out *APIShieldOperationParameters) {
	*out = *in
	if in.Endpoint != nil {
		in, out := &in.Endpoint, &out.Endpoint
		*out = new(string)
		**out = **in
	}
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = new(string)
		**out = **in
	}
	if in.Method != nil {
		in, out := &in.Method, &out.Method
		*out = new(string)
		**out = **in
	}
	if in.ZoneID != nil {
		in, out := &in.ZoneID, &out.ZoneID
		*out = new(string)
		**out = **in
	}
	if in.ZoneIDRef != nil {
		in, out := &in.ZoneIDRef, &out.ZoneIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ZoneIDSelector != nil {
		in, out := &in.ZoneIDSelector, &out.ZoneIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIShieldOperationParameters.
func (in *APIShieldOperationParameters) DeepCopy() *APIShieldOperationParameters {
	if in == nil {
		return nil
	}
	out := new(APIShieldOperationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIShieldOperationSchemaValidationSettings) DeepCopyInto(out *APIShieldOperationSchemaValidationSettings) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIShieldOperationSchemaValidationSettings.
func (in *APIShieldOperationSchemaValidationSettings) DeepCopy() *APIShieldOperationSchemaValidationSettings {
	if in == nil {
		return nil
	}
	out := new(APIShieldOperationSchemaValidationSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *APIShieldOperationSchemaValidationSettings) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIShieldOperationSchemaValidationSettingsInitParameters) DeepCopyInto(out *APIShieldOperationSchemaValidationSettingsInitParameters) {
	*out = *in
	if in.MitigationAction != nil {
		in, out := &in.MitigationAction, &out.MitigationAction
		*out = new(string)
		**out = **in
	}
	if in.OperationID != nil {
		in, out := &in.OperationID, &out.OperationID
		*out = new(string)
		**out = **in
	}
	if in.ZoneID != nil {
		in, out := &in.ZoneID, &out.ZoneID
		*out = new(string)
		**out = **in
	}
	if in.ZoneIDRef != nil {
		in, out := &in.ZoneIDRef, &out.ZoneIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ZoneIDSelector != nil {
		in, out := &in.ZoneIDSelector, &out.ZoneIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIShieldOperationSchemaValidationSettingsInitParameters.
func (in *APIShieldOperationSchemaValidationSettingsInitParameters) DeepCopy() *APIShieldOperationSchemaValidationSettingsInitParameters {
	if in == nil {
		return nil
	}
	out := new(APIShieldOperationSchemaValidationSettingsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIShieldOperationSchemaValidationSettingsList) DeepCopyInto(out *APIShieldOperationSchemaValidationSettingsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]APIShieldOperationSchemaValidationSettings, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIShieldOperationSchemaValidationSettingsList.
func (in *APIShieldOperationSchemaValidationSettingsList) DeepCopy() *APIShieldOperationSchemaValidationSettingsList {
	if in == nil {
		return nil
	}
	out := new(APIShieldOperationSchemaValidationSettingsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *APIShieldOperationSchemaValidationSettingsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIShieldOperationSchemaValidationSettingsObservation) DeepCopyInto(out *APIShieldOperationSchemaValidationSettingsObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.MitigationAction != nil {
		in, out := &in.MitigationAction, &out.MitigationAction
		*out = new(string)
		**out = **in
	}
	if in.OperationID != nil {
		in, out := &in.OperationID, &out.OperationID
		*out = new(string)
		**out = **in
	}
	if in.ZoneID != nil {
		in, out := &in.ZoneID, &out.ZoneID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIShieldOperationSchemaValidationSettingsObservation.
func (in *APIShieldOperationSchemaValidationSettingsObservation) DeepCopy() *APIShieldOperationSchemaValidationSettingsObservation {
	if in == nil {
		return nil
	}
	out := new(APIShieldOperationSchemaValidationSettingsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIShieldOperationSchemaValidationSettingsParameters) DeepCopyInto(out *APIShieldOperationSchemaValidationSettingsParameters) {
	*out = *in
	if in.MitigationAction != nil {
		in, out := &in.MitigationAction, &out.MitigationAction
		*out = new(string)
		**out = **in
	}
	if in.OperationID != nil {
		in, out := &in.OperationID, &out.OperationID
		*out = new(string)
		**out = **in
	}
	if in.ZoneID != nil {
		in, out := &in.ZoneID, &out.ZoneID
		*out = new(string)
		**out = **in
	}
	if in.ZoneIDRef != nil {
		in, out := &in.ZoneIDRef, &out.ZoneIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ZoneIDSelector != nil {
		in, out := &in.ZoneIDSelector, &out.ZoneIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIShieldOperationSchemaValidationSettingsParameters.
func (in *APIShieldOperationSchemaValidationSettingsParameters) DeepCopy() *APIShieldOperationSchemaValidationSettingsParameters {
	if in == nil {
		return nil
	}
	out := new(APIShieldOperationSchemaValidationSettingsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIShieldOperationSchemaValidationSettingsSpec) DeepCopyInto(out *APIShieldOperationSchemaValidationSettingsSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIShieldOperationSchemaValidationSettingsSpec.
func (in *APIShieldOperationSchemaValidationSettingsSpec) DeepCopy() *APIShieldOperationSchemaValidationSettingsSpec {
	if in == nil {
		return nil
	}
	out := new(APIShieldOperationSchemaValidationSettingsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIShieldOperationSchemaValidationSettingsStatus) DeepCopyInto(out *APIShieldOperationSchemaValidationSettingsStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIShieldOperationSchemaValidationSettingsStatus.
func (in *APIShieldOperationSchemaValidationSettingsStatus) DeepCopy() *APIShieldOperationSchemaValidationSettingsStatus {
	if in == nil {
		return nil
	}
	out := new(APIShieldOperationSchemaValidationSettingsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIShieldOperationSpec) DeepCopyInto(out *APIShieldOperationSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIShieldOperationSpec.
func (in *APIShieldOperationSpec) DeepCopy() *APIShieldOperationSpec {
	if in == nil {
		return nil
	}
	out := new(APIShieldOperationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIShieldOperationStatus) DeepCopyInto(out *APIShieldOperationStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIShieldOperationStatus.
func (in *APIShieldOperationStatus) DeepCopy() *APIShieldOperationStatus {
	if in == nil {
		return nil
	}
	out := new(APIShieldOperationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIShieldParameters) DeepCopyInto(out *APIShieldParameters) {
	*out = *in
	if in.AuthIDCharacteristics != nil {
		in, out := &in.AuthIDCharacteristics, &out.AuthIDCharacteristics
		*out = make([]AuthIDCharacteristicsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ZoneID != nil {
		in, out := &in.ZoneID, &out.ZoneID
		*out = new(string)
		**out = **in
	}
	if in.ZoneIDRef != nil {
		in, out := &in.ZoneIDRef, &out.ZoneIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ZoneIDSelector != nil {
		in, out := &in.ZoneIDSelector, &out.ZoneIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIShieldParameters.
func (in *APIShieldParameters) DeepCopy() *APIShieldParameters {
	if in == nil {
		return nil
	}
	out := new(APIShieldParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIShieldSchema) DeepCopyInto(out *APIShieldSchema) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIShieldSchema.
func (in *APIShieldSchema) DeepCopy() *APIShieldSchema {
	if in == nil {
		return nil
	}
	out := new(APIShieldSchema)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *APIShieldSchema) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIShieldSchemaInitParameters) DeepCopyInto(out *APIShieldSchemaInitParameters) {
	*out = *in
	if in.File != nil {
		in, out := &in.File, &out.File
		*out = new(string)
		**out = **in
	}
	if in.Kind != nil {
		in, out := &in.Kind, &out.Kind
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.SchemaID != nil {
		in, out := &in.SchemaID, &out.SchemaID
		*out = new(string)
		**out = **in
	}
	if in.ValidationEnabled != nil {
		in, out := &in.ValidationEnabled, &out.ValidationEnabled
		*out = new(string)
		**out = **in
	}
	if in.ZoneID != nil {
		in, out := &in.ZoneID, &out.ZoneID
		*out = new(string)
		**out = **in
	}
	if in.ZoneIDRef != nil {
		in, out := &in.ZoneIDRef, &out.ZoneIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ZoneIDSelector != nil {
		in, out := &in.ZoneIDSelector, &out.ZoneIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIShieldSchemaInitParameters.
func (in *APIShieldSchemaInitParameters) DeepCopy() *APIShieldSchemaInitParameters {
	if in == nil {
		return nil
	}
	out := new(APIShieldSchemaInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIShieldSchemaList) DeepCopyInto(out *APIShieldSchemaList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]APIShieldSchema, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIShieldSchemaList.
func (in *APIShieldSchemaList) DeepCopy() *APIShieldSchemaList {
	if in == nil {
		return nil
	}
	out := new(APIShieldSchemaList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *APIShieldSchemaList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIShieldSchemaObservation) DeepCopyInto(out *APIShieldSchemaObservation) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = new(string)
		**out = **in
	}
	if in.File != nil {
		in, out := &in.File, &out.File
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Kind != nil {
		in, out := &in.Kind, &out.Kind
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Schema != nil {
		in, out := &in.Schema, &out.Schema
		*out = new(SchemaObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.SchemaID != nil {
		in, out := &in.SchemaID, &out.SchemaID
		*out = new(string)
		**out = **in
	}
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(string)
		**out = **in
	}
	if in.UploadDetails != nil {
		in, out := &in.UploadDetails, &out.UploadDetails
		*out = new(UploadDetailsObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.ValidationEnabled != nil {
		in, out := &in.ValidationEnabled, &out.ValidationEnabled
		*out = new(string)
		**out = **in
	}
	if in.ZoneID != nil {
		in, out := &in.ZoneID, &out.ZoneID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIShieldSchemaObservation.
func (in *APIShieldSchemaObservation) DeepCopy() *APIShieldSchemaObservation {
	if in == nil {
		return nil
	}
	out := new(APIShieldSchemaObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIShieldSchemaParameters) DeepCopyInto(out *APIShieldSchemaParameters) {
	*out = *in
	if in.File != nil {
		in, out := &in.File, &out.File
		*out = new(string)
		**out = **in
	}
	if in.Kind != nil {
		in, out := &in.Kind, &out.Kind
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.SchemaID != nil {
		in, out := &in.SchemaID, &out.SchemaID
		*out = new(string)
		**out = **in
	}
	if in.ValidationEnabled != nil {
		in, out := &in.ValidationEnabled, &out.ValidationEnabled
		*out = new(string)
		**out = **in
	}
	if in.ZoneID != nil {
		in, out := &in.ZoneID, &out.ZoneID
		*out = new(string)
		**out = **in
	}
	if in.ZoneIDRef != nil {
		in, out := &in.ZoneIDRef, &out.ZoneIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ZoneIDSelector != nil {
		in, out := &in.ZoneIDSelector, &out.ZoneIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIShieldSchemaParameters.
func (in *APIShieldSchemaParameters) DeepCopy() *APIShieldSchemaParameters {
	if in == nil {
		return nil
	}
	out := new(APIShieldSchemaParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIShieldSchemaSpec) DeepCopyInto(out *APIShieldSchemaSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIShieldSchemaSpec.
func (in *APIShieldSchemaSpec) DeepCopy() *APIShieldSchemaSpec {
	if in == nil {
		return nil
	}
	out := new(APIShieldSchemaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIShieldSchemaStatus) DeepCopyInto(out *APIShieldSchemaStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIShieldSchemaStatus.
func (in *APIShieldSchemaStatus) DeepCopy() *APIShieldSchemaStatus {
	if in == nil {
		return nil
	}
	out := new(APIShieldSchemaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIShieldSchemaValidationSettings) DeepCopyInto(out *APIShieldSchemaValidationSettings) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIShieldSchemaValidationSettings.
func (in *APIShieldSchemaValidationSettings) DeepCopy() *APIShieldSchemaValidationSettings {
	if in == nil {
		return nil
	}
	out := new(APIShieldSchemaValidationSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *APIShieldSchemaValidationSettings) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIShieldSchemaValidationSettingsInitParameters) DeepCopyInto(out *APIShieldSchemaValidationSettingsInitParameters) {
	*out = *in
	if in.ValidationDefaultMitigationAction != nil {
		in, out := &in.ValidationDefaultMitigationAction, &out.ValidationDefaultMitigationAction
		*out = new(string)
		**out = **in
	}
	if in.ValidationOverrideMitigationAction != nil {
		in, out := &in.ValidationOverrideMitigationAction, &out.ValidationOverrideMitigationAction
		*out = new(string)
		**out = **in
	}
	if in.ZoneID != nil {
		in, out := &in.ZoneID, &out.ZoneID
		*out = new(string)
		**out = **in
	}
	if in.ZoneIDRef != nil {
		in, out := &in.ZoneIDRef, &out.ZoneIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ZoneIDSelector != nil {
		in, out := &in.ZoneIDSelector, &out.ZoneIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIShieldSchemaValidationSettingsInitParameters.
func (in *APIShieldSchemaValidationSettingsInitParameters) DeepCopy() *APIShieldSchemaValidationSettingsInitParameters {
	if in == nil {
		return nil
	}
	out := new(APIShieldSchemaValidationSettingsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIShieldSchemaValidationSettingsList) DeepCopyInto(out *APIShieldSchemaValidationSettingsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]APIShieldSchemaValidationSettings, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIShieldSchemaValidationSettingsList.
func (in *APIShieldSchemaValidationSettingsList) DeepCopy() *APIShieldSchemaValidationSettingsList {
	if in == nil {
		return nil
	}
	out := new(APIShieldSchemaValidationSettingsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *APIShieldSchemaValidationSettingsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIShieldSchemaValidationSettingsObservation) DeepCopyInto(out *APIShieldSchemaValidationSettingsObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.ValidationDefaultMitigationAction != nil {
		in, out := &in.ValidationDefaultMitigationAction, &out.ValidationDefaultMitigationAction
		*out = new(string)
		**out = **in
	}
	if in.ValidationOverrideMitigationAction != nil {
		in, out := &in.ValidationOverrideMitigationAction, &out.ValidationOverrideMitigationAction
		*out = new(string)
		**out = **in
	}
	if in.ZoneID != nil {
		in, out := &in.ZoneID, &out.ZoneID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIShieldSchemaValidationSettingsObservation.
func (in *APIShieldSchemaValidationSettingsObservation) DeepCopy() *APIShieldSchemaValidationSettingsObservation {
	if in == nil {
		return nil
	}
	out := new(APIShieldSchemaValidationSettingsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIShieldSchemaValidationSettingsParameters) DeepCopyInto(out *APIShieldSchemaValidationSettingsParameters) {
	*out = *in
	if in.ValidationDefaultMitigationAction != nil {
		in, out := &in.ValidationDefaultMitigationAction, &out.ValidationDefaultMitigationAction
		*out = new(string)
		**out = **in
	}
	if in.ValidationOverrideMitigationAction != nil {
		in, out := &in.ValidationOverrideMitigationAction, &out.ValidationOverrideMitigationAction
		*out = new(string)
		**out = **in
	}
	if in.ZoneID != nil {
		in, out := &in.ZoneID, &out.ZoneID
		*out = new(string)
		**out = **in
	}
	if in.ZoneIDRef != nil {
		in, out := &in.ZoneIDRef, &out.ZoneIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ZoneIDSelector != nil {
		in, out := &in.ZoneIDSelector, &out.ZoneIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIShieldSchemaValidationSettingsParameters.
func (in *APIShieldSchemaValidationSettingsParameters) DeepCopy() *APIShieldSchemaValidationSettingsParameters {
	if in == nil {
		return nil
	}
	out := new(APIShieldSchemaValidationSettingsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIShieldSchemaValidationSettingsSpec) DeepCopyInto(out *APIShieldSchemaValidationSettingsSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIShieldSchemaValidationSettingsSpec.
func (in *APIShieldSchemaValidationSettingsSpec) DeepCopy() *APIShieldSchemaValidationSettingsSpec {
	if in == nil {
		return nil
	}
	out := new(APIShieldSchemaValidationSettingsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIShieldSchemaValidationSettingsStatus) DeepCopyInto(out *APIShieldSchemaValidationSettingsStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIShieldSchemaValidationSettingsStatus.
func (in *APIShieldSchemaValidationSettingsStatus) DeepCopy() *APIShieldSchemaValidationSettingsStatus {
	if in == nil {
		return nil
	}
	out := new(APIShieldSchemaValidationSettingsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIShieldSpec) DeepCopyInto(out *APIShieldSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIShieldSpec.
func (in *APIShieldSpec) DeepCopy() *APIShieldSpec {
	if in == nil {
		return nil
	}
	out := new(APIShieldSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIShieldStatus) DeepCopyInto(out *APIShieldStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIShieldStatus.
func (in *APIShieldStatus) DeepCopy() *APIShieldStatus {
	if in == nil {
		return nil
	}
	out := new(APIShieldStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActiveSchemaInitParameters) DeepCopyInto(out *ActiveSchemaInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActiveSchemaInitParameters.
func (in *ActiveSchemaInitParameters) DeepCopy() *ActiveSchemaInitParameters {
	if in == nil {
		return nil
	}
	out := new(ActiveSchemaInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActiveSchemaObservation) DeepCopyInto(out *ActiveSchemaObservation) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IsLearned != nil {
		in, out := &in.IsLearned, &out.IsLearned
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActiveSchemaObservation.
func (in *ActiveSchemaObservation) DeepCopy() *ActiveSchemaObservation {
	if in == nil {
		return nil
	}
	out := new(ActiveSchemaObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActiveSchemaParameters) DeepCopyInto(out *ActiveSchemaParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActiveSchemaParameters.
func (in *ActiveSchemaParameters) DeepCopy() *ActiveSchemaParameters {
	if in == nil {
		return nil
	}
	out := new(ActiveSchemaParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthIDCharacteristicsInitParameters) DeepCopyInto(out *AuthIDCharacteristicsInitParameters) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthIDCharacteristicsInitParameters.
func (in *AuthIDCharacteristicsInitParameters) DeepCopy() *AuthIDCharacteristicsInitParameters {
	if in == nil {
		return nil
	}
	out := new(AuthIDCharacteristicsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthIDCharacteristicsObservation) DeepCopyInto(out *AuthIDCharacteristicsObservation) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthIDCharacteristicsObservation.
func (in *AuthIDCharacteristicsObservation) DeepCopy() *AuthIDCharacteristicsObservation {
	if in == nil {
		return nil
	}
	out := new(AuthIDCharacteristicsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthIDCharacteristicsParameters) DeepCopyInto(out *AuthIDCharacteristicsParameters) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthIDCharacteristicsParameters.
func (in *AuthIDCharacteristicsParameters) DeepCopy() *AuthIDCharacteristicsParameters {
	if in == nil {
		return nil
	}
	out := new(AuthIDCharacteristicsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfidenceIntervalsInitParameters) DeepCopyInto(out *ConfidenceIntervalsInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfidenceIntervalsInitParameters.
func (in *ConfidenceIntervalsInitParameters) DeepCopy() *ConfidenceIntervalsInitParameters {
	if in == nil {
		return nil
	}
	out := new(ConfidenceIntervalsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfidenceIntervalsObservation) DeepCopyInto(out *ConfidenceIntervalsObservation) {
	*out = *in
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = new(string)
		**out = **in
	}
	if in.SuggestedThreshold != nil {
		in, out := &in.SuggestedThreshold, &out.SuggestedThreshold
		*out = new(SuggestedThresholdObservation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfidenceIntervalsObservation.
func (in *ConfidenceIntervalsObservation) DeepCopy() *ConfidenceIntervalsObservation {
	if in == nil {
		return nil
	}
	out := new(ConfidenceIntervalsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfidenceIntervalsParameters) DeepCopyInto(out *ConfidenceIntervalsParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfidenceIntervalsParameters.
func (in *ConfidenceIntervalsParameters) DeepCopy() *ConfidenceIntervalsParameters {
	if in == nil {
		return nil
	}
	out := new(ConfidenceIntervalsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeaturesInitParameters) DeepCopyInto(out *FeaturesInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeaturesInitParameters.
func (in *FeaturesInitParameters) DeepCopy() *FeaturesInitParameters {
	if in == nil {
		return nil
	}
	out := new(FeaturesInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeaturesObservation) DeepCopyInto(out *FeaturesObservation) {
	*out = *in
	if in.APIRouting != nil {
		in, out := &in.APIRouting, &out.APIRouting
		*out = new(APIRoutingObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.ConfidenceIntervals != nil {
		in, out := &in.ConfidenceIntervals, &out.ConfidenceIntervals
		*out = new(ConfidenceIntervalsObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.ParameterSchemas != nil {
		in, out := &in.ParameterSchemas, &out.ParameterSchemas
		*out = new(ParameterSchemasObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.SchemaInfo != nil {
		in, out := &in.SchemaInfo, &out.SchemaInfo
		*out = new(SchemaInfoObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Thresholds != nil {
		in, out := &in.Thresholds, &out.Thresholds
		*out = new(ThresholdsObservation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeaturesObservation.
func (in *FeaturesObservation) DeepCopy() *FeaturesObservation {
	if in == nil {
		return nil
	}
	out := new(FeaturesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeaturesParameters) DeepCopyInto(out *FeaturesParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeaturesParameters.
func (in *FeaturesParameters) DeepCopy() *FeaturesParameters {
	if in == nil {
		return nil
	}
	out := new(FeaturesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *P90InitParameters) DeepCopyInto(out *P90InitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new P90InitParameters.
func (in *P90InitParameters) DeepCopy() *P90InitParameters {
	if in == nil {
		return nil
	}
	out := new(P90InitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *P90Observation) DeepCopyInto(out *P90Observation) {
	*out = *in
	if in.Lower != nil {
		in, out := &in.Lower, &out.Lower
		*out = new(float64)
		**out = **in
	}
	if in.Upper != nil {
		in, out := &in.Upper, &out.Upper
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new P90Observation.
func (in *P90Observation) DeepCopy() *P90Observation {
	if in == nil {
		return nil
	}
	out := new(P90Observation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *P90Parameters) DeepCopyInto(out *P90Parameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new P90Parameters.
func (in *P90Parameters) DeepCopy() *P90Parameters {
	if in == nil {
		return nil
	}
	out := new(P90Parameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *P95InitParameters) DeepCopyInto(out *P95InitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new P95InitParameters.
func (in *P95InitParameters) DeepCopy() *P95InitParameters {
	if in == nil {
		return nil
	}
	out := new(P95InitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *P95Observation) DeepCopyInto(out *P95Observation) {
	*out = *in
	if in.Lower != nil {
		in, out := &in.Lower, &out.Lower
		*out = new(float64)
		**out = **in
	}
	if in.Upper != nil {
		in, out := &in.Upper, &out.Upper
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new P95Observation.
func (in *P95Observation) DeepCopy() *P95Observation {
	if in == nil {
		return nil
	}
	out := new(P95Observation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *P95Parameters) DeepCopyInto(out *P95Parameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new P95Parameters.
func (in *P95Parameters) DeepCopy() *P95Parameters {
	if in == nil {
		return nil
	}
	out := new(P95Parameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *P99InitParameters) DeepCopyInto(out *P99InitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new P99InitParameters.
func (in *P99InitParameters) DeepCopy() *P99InitParameters {
	if in == nil {
		return nil
	}
	out := new(P99InitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *P99Observation) DeepCopyInto(out *P99Observation) {
	*out = *in
	if in.Lower != nil {
		in, out := &in.Lower, &out.Lower
		*out = new(float64)
		**out = **in
	}
	if in.Upper != nil {
		in, out := &in.Upper, &out.Upper
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new P99Observation.
func (in *P99Observation) DeepCopy() *P99Observation {
	if in == nil {
		return nil
	}
	out := new(P99Observation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *P99Parameters) DeepCopyInto(out *P99Parameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new P99Parameters.
func (in *P99Parameters) DeepCopy() *P99Parameters {
	if in == nil {
		return nil
	}
	out := new(P99Parameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParameterSchemasInitParameters) DeepCopyInto(out *ParameterSchemasInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParameterSchemasInitParameters.
func (in *ParameterSchemasInitParameters) DeepCopy() *ParameterSchemasInitParameters {
	if in == nil {
		return nil
	}
	out := new(ParameterSchemasInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParameterSchemasObservation) DeepCopyInto(out *ParameterSchemasObservation) {
	*out = *in
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = new(string)
		**out = **in
	}
	if in.ParameterSchemas != nil {
		in, out := &in.ParameterSchemas, &out.ParameterSchemas
		*out = new(ParameterSchemasParameterSchemasObservation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParameterSchemasObservation.
func (in *ParameterSchemasObservation) DeepCopy() *ParameterSchemasObservation {
	if in == nil {
		return nil
	}
	out := new(ParameterSchemasObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParameterSchemasParameterSchemasInitParameters) DeepCopyInto(out *ParameterSchemasParameterSchemasInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParameterSchemasParameterSchemasInitParameters.
func (in *ParameterSchemasParameterSchemasInitParameters) DeepCopy() *ParameterSchemasParameterSchemasInitParameters {
	if in == nil {
		return nil
	}
	out := new(ParameterSchemasParameterSchemasInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParameterSchemasParameterSchemasObservation) DeepCopyInto(out *ParameterSchemasParameterSchemasObservation) {
	*out = *in
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Responses != nil {
		in, out := &in.Responses, &out.Responses
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParameterSchemasParameterSchemasObservation.
func (in *ParameterSchemasParameterSchemasObservation) DeepCopy() *ParameterSchemasParameterSchemasObservation {
	if in == nil {
		return nil
	}
	out := new(ParameterSchemasParameterSchemasObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParameterSchemasParameterSchemasParameters) DeepCopyInto(out *ParameterSchemasParameterSchemasParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParameterSchemasParameterSchemasParameters.
func (in *ParameterSchemasParameterSchemasParameters) DeepCopy() *ParameterSchemasParameterSchemasParameters {
	if in == nil {
		return nil
	}
	out := new(ParameterSchemasParameterSchemasParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParameterSchemasParameters) DeepCopyInto(out *ParameterSchemasParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParameterSchemasParameters.
func (in *ParameterSchemasParameters) DeepCopy() *ParameterSchemasParameters {
	if in == nil {
		return nil
	}
	out := new(ParameterSchemasParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchemaInfoInitParameters) DeepCopyInto(out *SchemaInfoInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchemaInfoInitParameters.
func (in *SchemaInfoInitParameters) DeepCopy() *SchemaInfoInitParameters {
	if in == nil {
		return nil
	}
	out := new(SchemaInfoInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchemaInfoObservation) DeepCopyInto(out *SchemaInfoObservation) {
	*out = *in
	if in.ActiveSchema != nil {
		in, out := &in.ActiveSchema, &out.ActiveSchema
		*out = new(ActiveSchemaObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.LearnedAvailable != nil {
		in, out := &in.LearnedAvailable, &out.LearnedAvailable
		*out = new(bool)
		**out = **in
	}
	if in.MitigationAction != nil {
		in, out := &in.MitigationAction, &out.MitigationAction
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchemaInfoObservation.
func (in *SchemaInfoObservation) DeepCopy() *SchemaInfoObservation {
	if in == nil {
		return nil
	}
	out := new(SchemaInfoObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchemaInfoParameters) DeepCopyInto(out *SchemaInfoParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchemaInfoParameters.
func (in *SchemaInfoParameters) DeepCopy() *SchemaInfoParameters {
	if in == nil {
		return nil
	}
	out := new(SchemaInfoParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchemaInitParameters) DeepCopyInto(out *SchemaInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchemaInitParameters.
func (in *SchemaInitParameters) DeepCopy() *SchemaInitParameters {
	if in == nil {
		return nil
	}
	out := new(SchemaInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchemaObservation) DeepCopyInto(out *SchemaObservation) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = new(string)
		**out = **in
	}
	if in.Kind != nil {
		in, out := &in.Kind, &out.Kind
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.SchemaID != nil {
		in, out := &in.SchemaID, &out.SchemaID
		*out = new(string)
		**out = **in
	}
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(string)
		**out = **in
	}
	if in.ValidationEnabled != nil {
		in, out := &in.ValidationEnabled, &out.ValidationEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchemaObservation.
func (in *SchemaObservation) DeepCopy() *SchemaObservation {
	if in == nil {
		return nil
	}
	out := new(SchemaObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchemaParameters) DeepCopyInto(out *SchemaParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchemaParameters.
func (in *SchemaParameters) DeepCopy() *SchemaParameters {
	if in == nil {
		return nil
	}
	out := new(SchemaParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SuggestedThresholdConfidenceIntervalsInitParameters) DeepCopyInto(out *SuggestedThresholdConfidenceIntervalsInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SuggestedThresholdConfidenceIntervalsInitParameters.
func (in *SuggestedThresholdConfidenceIntervalsInitParameters) DeepCopy() *SuggestedThresholdConfidenceIntervalsInitParameters {
	if in == nil {
		return nil
	}
	out := new(SuggestedThresholdConfidenceIntervalsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SuggestedThresholdConfidenceIntervalsObservation) DeepCopyInto(out *SuggestedThresholdConfidenceIntervalsObservation) {
	*out = *in
	if in.P90 != nil {
		in, out := &in.P90, &out.P90
		*out = new(P90Observation)
		(*in).DeepCopyInto(*out)
	}
	if in.P95 != nil {
		in, out := &in.P95, &out.P95
		*out = new(P95Observation)
		(*in).DeepCopyInto(*out)
	}
	if in.P99 != nil {
		in, out := &in.P99, &out.P99
		*out = new(P99Observation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SuggestedThresholdConfidenceIntervalsObservation.
func (in *SuggestedThresholdConfidenceIntervalsObservation) DeepCopy() *SuggestedThresholdConfidenceIntervalsObservation {
	if in == nil {
		return nil
	}
	out := new(SuggestedThresholdConfidenceIntervalsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SuggestedThresholdConfidenceIntervalsParameters) DeepCopyInto(out *SuggestedThresholdConfidenceIntervalsParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SuggestedThresholdConfidenceIntervalsParameters.
func (in *SuggestedThresholdConfidenceIntervalsParameters) DeepCopy() *SuggestedThresholdConfidenceIntervalsParameters {
	if in == nil {
		return nil
	}
	out := new(SuggestedThresholdConfidenceIntervalsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SuggestedThresholdInitParameters) DeepCopyInto(out *SuggestedThresholdInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SuggestedThresholdInitParameters.
func (in *SuggestedThresholdInitParameters) DeepCopy() *SuggestedThresholdInitParameters {
	if in == nil {
		return nil
	}
	out := new(SuggestedThresholdInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SuggestedThresholdObservation) DeepCopyInto(out *SuggestedThresholdObservation) {
	*out = *in
	if in.ConfidenceIntervals != nil {
		in, out := &in.ConfidenceIntervals, &out.ConfidenceIntervals
		*out = new(SuggestedThresholdConfidenceIntervalsObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Mean != nil {
		in, out := &in.Mean, &out.Mean
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SuggestedThresholdObservation.
func (in *SuggestedThresholdObservation) DeepCopy() *SuggestedThresholdObservation {
	if in == nil {
		return nil
	}
	out := new(SuggestedThresholdObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SuggestedThresholdParameters) DeepCopyInto(out *SuggestedThresholdParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SuggestedThresholdParameters.
func (in *SuggestedThresholdParameters) DeepCopy() *SuggestedThresholdParameters {
	if in == nil {
		return nil
	}
	out := new(SuggestedThresholdParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThresholdsInitParameters) DeepCopyInto(out *ThresholdsInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThresholdsInitParameters.
func (in *ThresholdsInitParameters) DeepCopy() *ThresholdsInitParameters {
	if in == nil {
		return nil
	}
	out := new(ThresholdsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThresholdsObservation) DeepCopyInto(out *ThresholdsObservation) {
	*out = *in
	if in.AuthIDTokens != nil {
		in, out := &in.AuthIDTokens, &out.AuthIDTokens
		*out = new(float64)
		**out = **in
	}
	if in.DataPoints != nil {
		in, out := &in.DataPoints, &out.DataPoints
		*out = new(float64)
		**out = **in
	}
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = new(string)
		**out = **in
	}
	if in.P50 != nil {
		in, out := &in.P50, &out.P50
		*out = new(float64)
		**out = **in
	}
	if in.P90 != nil {
		in, out := &in.P90, &out.P90
		*out = new(float64)
		**out = **in
	}
	if in.P99 != nil {
		in, out := &in.P99, &out.P99
		*out = new(float64)
		**out = **in
	}
	if in.PeriodSeconds != nil {
		in, out := &in.PeriodSeconds, &out.PeriodSeconds
		*out = new(float64)
		**out = **in
	}
	if in.Requests != nil {
		in, out := &in.Requests, &out.Requests
		*out = new(float64)
		**out = **in
	}
	if in.SuggestedThreshold != nil {
		in, out := &in.SuggestedThreshold, &out.SuggestedThreshold
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThresholdsObservation.
func (in *ThresholdsObservation) DeepCopy() *ThresholdsObservation {
	if in == nil {
		return nil
	}
	out := new(ThresholdsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThresholdsParameters) DeepCopyInto(out *ThresholdsParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThresholdsParameters.
func (in *ThresholdsParameters) DeepCopy() *ThresholdsParameters {
	if in == nil {
		return nil
	}
	out := new(ThresholdsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UploadDetailsInitParameters) DeepCopyInto(out *UploadDetailsInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UploadDetailsInitParameters.
func (in *UploadDetailsInitParameters) DeepCopy() *UploadDetailsInitParameters {
	if in == nil {
		return nil
	}
	out := new(UploadDetailsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UploadDetailsObservation) DeepCopyInto(out *UploadDetailsObservation) {
	*out = *in
	if in.Warnings != nil {
		in, out := &in.Warnings, &out.Warnings
		*out = make([]WarningsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UploadDetailsObservation.
func (in *UploadDetailsObservation) DeepCopy() *UploadDetailsObservation {
	if in == nil {
		return nil
	}
	out := new(UploadDetailsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UploadDetailsParameters) DeepCopyInto(out *UploadDetailsParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UploadDetailsParameters.
func (in *UploadDetailsParameters) DeepCopy() *UploadDetailsParameters {
	if in == nil {
		return nil
	}
	out := new(UploadDetailsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarningsInitParameters) DeepCopyInto(out *WarningsInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarningsInitParameters.
func (in *WarningsInitParameters) DeepCopy() *WarningsInitParameters {
	if in == nil {
		return nil
	}
	out := new(WarningsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarningsObservation) DeepCopyInto(out *WarningsObservation) {
	*out = *in
	if in.Code != nil {
		in, out := &in.Code, &out.Code
		*out = new(float64)
		**out = **in
	}
	if in.Locations != nil {
		in, out := &in.Locations, &out.Locations
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarningsObservation.
func (in *WarningsObservation) DeepCopy() *WarningsObservation {
	if in == nil {
		return nil
	}
	out := new(WarningsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarningsParameters) DeepCopyInto(out *WarningsParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarningsParameters.
func (in *WarningsParameters) DeepCopy() *WarningsParameters {
	if in == nil {
		return nil
	}
	out := new(WarningsParameters)
	in.DeepCopyInto(out)
	return out
}
