apiVersion: misc.cloudflare.crossplane.io/v1alpha1
kind: CloudConnectorRules
metadata:
  annotations:
    meta.upbound.io/example-id: misc/v1alpha1/cloudconnectorrules
  labels:
    testing.upbound.io/example-name: example_cloud_connector_rules
  name: example-cloud-connector-rules
spec:
  forProvider:
    rules:
    - cloud_connector_rules_provider: aws_s3
      description: Rule description
      enabled: true
      expression: http.cookie eq "a=b"
      parameters:
        host: examplebucket.s3.eu-north-1.amazonaws.com
    zoneIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
