apiVersion: email.cloudflare.crossplane.io/v1alpha1
kind: EmailRoutingDNS
metadata:
  annotations:
    meta.upbound.io/example-id: email/v1alpha1/emailroutingdns
  labels:
    testing.upbound.io/example-name: example_email_routing_dns
  name: example-email-routing-dns
spec:
  forProvider:
    name: example.net
    zoneIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
