apiVersion: workers.cloudflare.m.cloudflare.com/v1alpha1
kind: WorkersScript
metadata:
  annotations:
    meta.upbound.io/example-id: workers/v1alpha1/workersscript
  labels:
    testing.upbound.io/example-name: example_workers_script
  name: example-workers-script
  namespace: crossplane-system
spec:
  forProvider:
    accountIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    assets:
      config:
        headers: |2
                  /dashboard/*
                  X-Frame-Options: DENY

                  /static/*
                  Access-Control-Allow-Origin: *
        htmlHandling: auto-trailing-slash
        notFoundHandling: none
        redirects: |2
                  /foo /bar 301
                  /news/* /blog/:splat
        runWorkerFirst: false
      jwtSecretRef:
        key: example-key
        name: example-secret
    bindings:
    - name: MY_ENV_VAR
      textSecretRef:
        key: example-key
        name: example-secret
      type: plain_text
    compatibilityDate: "2021-01-01"
    compatibilityFlags:
    - nodejs_compat
    contentFile: worker.js
    contentSha256: ${filesha256("worker.js")}
    keepAssets: false
    keepBindings:
    - kv_namespace
    limits:
      cpuMs: 50
    logpush: false
    mainModule: worker.js
    migrations:
      deletedClasses:
      - string
      newClasses:
      - string
      newSqliteClasses:
      - string
      newTag: v2
      oldTag: v1
      renamedClasses:
      - from: from
        to: to
      transferredClasses:
      - from: from
        fromScript: from_script
        to: to
    observability:
      enabled: true
      headSamplingRate: 0.1
      logs:
        destinations:
        - cloudflare
        enabled: true
        headSamplingRate: 0.1
        invocationLogs: true
        persist: true
    placement:
      mode: smart
    scriptName: this-is_my_script-01
    tailConsumers:
    - environment: production
      namespace: my-namespace
      service: my-log-consumer
