// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type R2BucketLockInitParameters struct {

	// (String) Account ID.
	// Account ID.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/cluster/account/v1alpha1.Account
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// Reference to a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDRef *v1.Reference `json:"accountIdRef,omitempty" tf:"-"`

	// Selector for a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDSelector *v1.Selector `json:"accountIdSelector,omitempty" tf:"-"`

	// (String) Name of the bucket.
	// Name of the bucket.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/cluster/r2/v1alpha1.R2Bucket
	BucketName *string `json:"bucketName,omitempty" tf:"bucket_name,omitempty"`

	// Reference to a R2Bucket in r2 to populate bucketName.
	// +kubebuilder:validation:Optional
	BucketNameRef *v1.Reference `json:"bucketNameRef,omitempty" tf:"-"`

	// Selector for a R2Bucket in r2 to populate bucketName.
	// +kubebuilder:validation:Optional
	BucketNameSelector *v1.Selector `json:"bucketNameSelector,omitempty" tf:"-"`

	// (String) Jurisdiction of the bucket
	// Jurisdiction of the bucket
	Jurisdiction *string `json:"jurisdiction,omitempty" tf:"jurisdiction,omitempty"`

	// (Attributes List) (see below for nested schema)
	Rules []R2BucketLockRulesInitParameters `json:"rules,omitempty" tf:"rules,omitempty"`
}

type R2BucketLockObservation struct {

	// (String) Account ID.
	// Account ID.
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// (String) Name of the bucket.
	// Name of the bucket.
	BucketName *string `json:"bucketName,omitempty" tf:"bucket_name,omitempty"`

	// (String) Unique identifier for this rule.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Jurisdiction of the bucket
	// Jurisdiction of the bucket
	Jurisdiction *string `json:"jurisdiction,omitempty" tf:"jurisdiction,omitempty"`

	// (Attributes List) (see below for nested schema)
	Rules []R2BucketLockRulesObservation `json:"rules,omitempty" tf:"rules,omitempty"`
}

type R2BucketLockParameters struct {

	// (String) Account ID.
	// Account ID.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/cluster/account/v1alpha1.Account
	// +kubebuilder:validation:Optional
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// Reference to a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDRef *v1.Reference `json:"accountIdRef,omitempty" tf:"-"`

	// Selector for a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDSelector *v1.Selector `json:"accountIdSelector,omitempty" tf:"-"`

	// (String) Name of the bucket.
	// Name of the bucket.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/cluster/r2/v1alpha1.R2Bucket
	// +kubebuilder:validation:Optional
	BucketName *string `json:"bucketName,omitempty" tf:"bucket_name,omitempty"`

	// Reference to a R2Bucket in r2 to populate bucketName.
	// +kubebuilder:validation:Optional
	BucketNameRef *v1.Reference `json:"bucketNameRef,omitempty" tf:"-"`

	// Selector for a R2Bucket in r2 to populate bucketName.
	// +kubebuilder:validation:Optional
	BucketNameSelector *v1.Selector `json:"bucketNameSelector,omitempty" tf:"-"`

	// (String) Jurisdiction of the bucket
	// Jurisdiction of the bucket
	// +kubebuilder:validation:Optional
	Jurisdiction *string `json:"jurisdiction,omitempty" tf:"jurisdiction,omitempty"`

	// (Attributes List) (see below for nested schema)
	// +kubebuilder:validation:Optional
	Rules []R2BucketLockRulesParameters `json:"rules,omitempty" tf:"rules,omitempty"`
}

type R2BucketLockRulesInitParameters struct {

	// (Attributes) Condition to apply a lock rule to an object for how long in seconds. (see below for nested schema)
	Condition *RulesConditionInitParameters `json:"condition,omitempty" tf:"condition,omitempty"`

	// (Boolean) Whether or not this rule is in effect.
	// Whether or not this rule is in effect.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) Unique identifier for this rule.
	// Unique identifier for this rule.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Rule will only apply to objects/uploads in the bucket that start with the given prefix, an empty prefix can be provided to scope rule to all objects/uploads.
	// Rule will only apply to objects/uploads in the bucket that start with the given prefix, an empty prefix can be provided to scope rule to all objects/uploads.
	Prefix *string `json:"prefix,omitempty" tf:"prefix,omitempty"`
}

type R2BucketLockRulesObservation struct {

	// (Attributes) Condition to apply a lock rule to an object for how long in seconds. (see below for nested schema)
	Condition *RulesConditionObservation `json:"condition,omitempty" tf:"condition,omitempty"`

	// (Boolean) Whether or not this rule is in effect.
	// Whether or not this rule is in effect.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) Unique identifier for this rule.
	// Unique identifier for this rule.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Rule will only apply to objects/uploads in the bucket that start with the given prefix, an empty prefix can be provided to scope rule to all objects/uploads.
	// Rule will only apply to objects/uploads in the bucket that start with the given prefix, an empty prefix can be provided to scope rule to all objects/uploads.
	Prefix *string `json:"prefix,omitempty" tf:"prefix,omitempty"`
}

type R2BucketLockRulesParameters struct {

	// (Attributes) Condition to apply a lock rule to an object for how long in seconds. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Condition *RulesConditionParameters `json:"condition" tf:"condition,omitempty"`

	// (Boolean) Whether or not this rule is in effect.
	// Whether or not this rule is in effect.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled" tf:"enabled,omitempty"`

	// (String) Unique identifier for this rule.
	// Unique identifier for this rule.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`

	// (String) Rule will only apply to objects/uploads in the bucket that start with the given prefix, an empty prefix can be provided to scope rule to all objects/uploads.
	// Rule will only apply to objects/uploads in the bucket that start with the given prefix, an empty prefix can be provided to scope rule to all objects/uploads.
	// +kubebuilder:validation:Optional
	Prefix *string `json:"prefix,omitempty" tf:"prefix,omitempty"`
}

type RulesConditionInitParameters struct {

	// (String)
	Date *string `json:"date,omitempty" tf:"date,omitempty"`

	// (Number)
	MaxAgeSeconds *float64 `json:"maxAgeSeconds,omitempty" tf:"max_age_seconds,omitempty"`

	// (String) Available values: "Age", "Date", "Indefinite".
	// Available values: "Age", "Date", "Indefinite".
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type RulesConditionObservation struct {

	// (String)
	Date *string `json:"date,omitempty" tf:"date,omitempty"`

	// (Number)
	MaxAgeSeconds *float64 `json:"maxAgeSeconds,omitempty" tf:"max_age_seconds,omitempty"`

	// (String) Available values: "Age", "Date", "Indefinite".
	// Available values: "Age", "Date", "Indefinite".
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type RulesConditionParameters struct {

	// (String)
	// +kubebuilder:validation:Optional
	Date *string `json:"date,omitempty" tf:"date,omitempty"`

	// (Number)
	// +kubebuilder:validation:Optional
	MaxAgeSeconds *float64 `json:"maxAgeSeconds,omitempty" tf:"max_age_seconds,omitempty"`

	// (String) Available values: "Age", "Date", "Indefinite".
	// Available values: "Age", "Date", "Indefinite".
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`
}

// R2BucketLockSpec defines the desired state of R2BucketLock
type R2BucketLockSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     R2BucketLockParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider R2BucketLockInitParameters `json:"initProvider,omitempty"`
}

// R2BucketLockStatus defines the observed state of R2BucketLock.
type R2BucketLockStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        R2BucketLockObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// R2BucketLock is the Schema for the R2BucketLocks API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudflare}
type R2BucketLock struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              R2BucketLockSpec   `json:"spec"`
	Status            R2BucketLockStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// R2BucketLockList contains a list of R2BucketLocks
type R2BucketLockList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []R2BucketLock `json:"items"`
}

// Repository type metadata.
var (
	R2BucketLock_Kind             = "R2BucketLock"
	R2BucketLock_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: R2BucketLock_Kind}.String()
	R2BucketLock_KindAPIVersion   = R2BucketLock_Kind + "." + CRDGroupVersion.String()
	R2BucketLock_GroupVersionKind = CRDGroupVersion.WithKind(R2BucketLock_Kind)
)

func init() {
	SchemeBuilder.Register(&R2BucketLock{}, &R2BucketLockList{})
}
