// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type R2CustomDomainInitParameters struct {

	// (String) Account ID.
	// Account ID.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/cluster/account/v1alpha1.Account
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// Reference to a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDRef *v1.Reference `json:"accountIdRef,omitempty" tf:"-"`

	// Selector for a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDSelector *v1.Selector `json:"accountIdSelector,omitempty" tf:"-"`

	// (String) Name of the bucket.
	// Name of the bucket.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/cluster/r2/v1alpha1.R2Bucket
	BucketName *string `json:"bucketName,omitempty" tf:"bucket_name,omitempty"`

	// Reference to a R2Bucket in r2 to populate bucketName.
	// +kubebuilder:validation:Optional
	BucketNameRef *v1.Reference `json:"bucketNameRef,omitempty" tf:"-"`

	// Selector for a R2Bucket in r2 to populate bucketName.
	// +kubebuilder:validation:Optional
	BucketNameSelector *v1.Selector `json:"bucketNameSelector,omitempty" tf:"-"`

	// (List of String) An allowlist of ciphers for TLS termination. These ciphers must be in the BoringSSL format.
	// An allowlist of ciphers for TLS termination. These ciphers must be in the BoringSSL format.
	Ciphers []*string `json:"ciphers,omitempty" tf:"ciphers,omitempty"`

	// (String) Name of the custom domain to be added.
	// Name of the custom domain to be added.
	Domain *string `json:"domain,omitempty" tf:"domain,omitempty"`

	// (Boolean) Whether to enable public bucket access at the custom domain. If undefined, the domain will be enabled.
	// Whether to enable public bucket access at the custom domain. If undefined, the domain will be enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) Jurisdiction of the bucket
	// Jurisdiction of the bucket
	Jurisdiction *string `json:"jurisdiction,omitempty" tf:"jurisdiction,omitempty"`

	// (String) Minimum TLS Version the custom domain will accept for incoming connections. If not set, defaults to 1.0.
	// Available values: "1.0", "1.1", "1.2", "1.3".
	// Minimum TLS Version the custom domain will accept for incoming connections. If not set, defaults to 1.0.
	// Available values: "1.0", "1.1", "1.2", "1.3".
	MinTLS *string `json:"minTls,omitempty" tf:"min_tls,omitempty"`

	// (String) Zone ID of the custom domain.
	// Zone ID of the custom domain.
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`
}

type R2CustomDomainObservation struct {

	// (String) Account ID.
	// Account ID.
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// (String) Name of the bucket.
	// Name of the bucket.
	BucketName *string `json:"bucketName,omitempty" tf:"bucket_name,omitempty"`

	// (List of String) An allowlist of ciphers for TLS termination. These ciphers must be in the BoringSSL format.
	// An allowlist of ciphers for TLS termination. These ciphers must be in the BoringSSL format.
	Ciphers []*string `json:"ciphers,omitempty" tf:"ciphers,omitempty"`

	// (String) Name of the custom domain to be added.
	// Name of the custom domain to be added.
	Domain *string `json:"domain,omitempty" tf:"domain,omitempty"`

	// (Boolean) Whether to enable public bucket access at the custom domain. If undefined, the domain will be enabled.
	// Whether to enable public bucket access at the custom domain. If undefined, the domain will be enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Jurisdiction of the bucket
	// Jurisdiction of the bucket
	Jurisdiction *string `json:"jurisdiction,omitempty" tf:"jurisdiction,omitempty"`

	// (String) Minimum TLS Version the custom domain will accept for incoming connections. If not set, defaults to 1.0.
	// Available values: "1.0", "1.1", "1.2", "1.3".
	// Minimum TLS Version the custom domain will accept for incoming connections. If not set, defaults to 1.0.
	// Available values: "1.0", "1.1", "1.2", "1.3".
	MinTLS *string `json:"minTls,omitempty" tf:"min_tls,omitempty"`

	// (Attributes) (see below for nested schema)
	Status *StatusObservation `json:"status,omitempty" tf:"status,omitempty"`

	// (String) Zone ID of the custom domain.
	// Zone ID of the custom domain.
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`

	// (String) Zone that the custom domain resides in.
	// Zone that the custom domain resides in.
	ZoneName *string `json:"zoneName,omitempty" tf:"zone_name,omitempty"`
}

type R2CustomDomainParameters struct {

	// (String) Account ID.
	// Account ID.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/cluster/account/v1alpha1.Account
	// +kubebuilder:validation:Optional
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// Reference to a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDRef *v1.Reference `json:"accountIdRef,omitempty" tf:"-"`

	// Selector for a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDSelector *v1.Selector `json:"accountIdSelector,omitempty" tf:"-"`

	// (String) Name of the bucket.
	// Name of the bucket.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/cluster/r2/v1alpha1.R2Bucket
	// +kubebuilder:validation:Optional
	BucketName *string `json:"bucketName,omitempty" tf:"bucket_name,omitempty"`

	// Reference to a R2Bucket in r2 to populate bucketName.
	// +kubebuilder:validation:Optional
	BucketNameRef *v1.Reference `json:"bucketNameRef,omitempty" tf:"-"`

	// Selector for a R2Bucket in r2 to populate bucketName.
	// +kubebuilder:validation:Optional
	BucketNameSelector *v1.Selector `json:"bucketNameSelector,omitempty" tf:"-"`

	// (List of String) An allowlist of ciphers for TLS termination. These ciphers must be in the BoringSSL format.
	// An allowlist of ciphers for TLS termination. These ciphers must be in the BoringSSL format.
	// +kubebuilder:validation:Optional
	Ciphers []*string `json:"ciphers,omitempty" tf:"ciphers,omitempty"`

	// (String) Name of the custom domain to be added.
	// Name of the custom domain to be added.
	// +kubebuilder:validation:Optional
	Domain *string `json:"domain,omitempty" tf:"domain,omitempty"`

	// (Boolean) Whether to enable public bucket access at the custom domain. If undefined, the domain will be enabled.
	// Whether to enable public bucket access at the custom domain. If undefined, the domain will be enabled.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) Jurisdiction of the bucket
	// Jurisdiction of the bucket
	// +kubebuilder:validation:Optional
	Jurisdiction *string `json:"jurisdiction,omitempty" tf:"jurisdiction,omitempty"`

	// (String) Minimum TLS Version the custom domain will accept for incoming connections. If not set, defaults to 1.0.
	// Available values: "1.0", "1.1", "1.2", "1.3".
	// Minimum TLS Version the custom domain will accept for incoming connections. If not set, defaults to 1.0.
	// Available values: "1.0", "1.1", "1.2", "1.3".
	// +kubebuilder:validation:Optional
	MinTLS *string `json:"minTls,omitempty" tf:"min_tls,omitempty"`

	// (String) Zone ID of the custom domain.
	// Zone ID of the custom domain.
	// +kubebuilder:validation:Optional
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`
}

type StatusInitParameters struct {
}

type StatusObservation struct {

	// (String) Ownership status of the domain.
	// Available values: "pending", "active", "deactivated", "blocked", "error", "unknown".
	// Ownership status of the domain.
	// Available values: "pending", "active", "deactivated", "blocked", "error", "unknown".
	Ownership *string `json:"ownership,omitempty" tf:"ownership,omitempty"`

	// (String) SSL certificate status.
	// Available values: "initializing", "pending", "active", "deactivated", "error", "unknown".
	// SSL certificate status.
	// Available values: "initializing", "pending", "active", "deactivated", "error", "unknown".
	SSL *string `json:"ssl,omitempty" tf:"ssl,omitempty"`
}

type StatusParameters struct {
}

// R2CustomDomainSpec defines the desired state of R2CustomDomain
type R2CustomDomainSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     R2CustomDomainParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider R2CustomDomainInitParameters `json:"initProvider,omitempty"`
}

// R2CustomDomainStatus defines the observed state of R2CustomDomain.
type R2CustomDomainStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        R2CustomDomainObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// R2CustomDomain is the Schema for the R2CustomDomains API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudflare}
type R2CustomDomain struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.domain) || (has(self.initProvider) && has(self.initProvider.domain))",message="spec.forProvider.domain is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.enabled) || (has(self.initProvider) && has(self.initProvider.enabled))",message="spec.forProvider.enabled is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.zoneId) || (has(self.initProvider) && has(self.initProvider.zoneId))",message="spec.forProvider.zoneId is a required parameter"
	Spec   R2CustomDomainSpec   `json:"spec"`
	Status R2CustomDomainStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// R2CustomDomainList contains a list of R2CustomDomains
type R2CustomDomainList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []R2CustomDomain `json:"items"`
}

// Repository type metadata.
var (
	R2CustomDomain_Kind             = "R2CustomDomain"
	R2CustomDomain_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: R2CustomDomain_Kind}.String()
	R2CustomDomain_KindAPIVersion   = R2CustomDomain_Kind + "." + CRDGroupVersion.String()
	R2CustomDomain_GroupVersionKind = CRDGroupVersion.WithKind(R2CustomDomain_Kind)
)

func init() {
	SchemeBuilder.Register(&R2CustomDomain{}, &R2CustomDomainList{})
}
