apiVersion: zerotrust.cloudflare.crossplane.io/v1alpha1
kind: ZeroTrustDLPCustomEntry
metadata:
  annotations:
    meta.upbound.io/example-id: zerotrust/v1alpha1/zerotrustdlpcustomentry
  labels:
    testing.upbound.io/example-name: example_zero_trust_dlp_custom_entry
  name: example-zero-trust-dlp-custom-entry
spec:
  forProvider:
    accountIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    enabled: true
    name: name
    pattern:
      regex: regex
      validation: luhn
    profileId: 182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e
