// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type EmailRoutingRuleActionsInitParameters struct {

	// (String) Type of supported action.
	// Available values: "drop", "forward", "worker".
	// Type of supported action.
	// Available values: "drop", "forward", "worker".
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (List of String)
	Value []*string `json:"value,omitempty" tf:"value,omitempty"`
}

type EmailRoutingRuleActionsObservation struct {

	// (String) Type of supported action.
	// Available values: "drop", "forward", "worker".
	// Type of supported action.
	// Available values: "drop", "forward", "worker".
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (List of String)
	Value []*string `json:"value,omitempty" tf:"value,omitempty"`
}

type EmailRoutingRuleActionsParameters struct {

	// (String) Type of supported action.
	// Available values: "drop", "forward", "worker".
	// Type of supported action.
	// Available values: "drop", "forward", "worker".
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`

	// (List of String)
	// +kubebuilder:validation:Optional
	Value []*string `json:"value,omitempty" tf:"value,omitempty"`
}

type EmailRoutingRuleInitParameters struct {

	// (Attributes List) List actions patterns. (see below for nested schema)
	Actions []EmailRoutingRuleActionsInitParameters `json:"actions,omitempty" tf:"actions,omitempty"`

	// (Boolean) Routing rule status.
	// Routing rule status.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Attributes List) Matching patterns to forward to your actions. (see below for nested schema)
	Matchers []EmailRoutingRuleMatchersInitParameters `json:"matchers,omitempty" tf:"matchers,omitempty"`

	// (String) Routing rule name.
	// Routing rule name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) Priority of the routing rule.
	// Priority of the routing rule.
	Priority *float64 `json:"priority,omitempty" tf:"priority,omitempty"`

	// (String) Identifier.
	// Identifier.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/zone/v1alpha1.Zone
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`

	// Reference to a Zone in zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDRef *v1.NamespacedReference `json:"zoneIdRef,omitempty" tf:"-"`

	// Selector for a Zone in zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDSelector *v1.NamespacedSelector `json:"zoneIdSelector,omitempty" tf:"-"`
}

type EmailRoutingRuleMatchersInitParameters struct {

	// (String) Field for type matcher.
	// Available values: "to".
	// Field for type matcher.
	// Available values: "to".
	Field *string `json:"field,omitempty" tf:"field,omitempty"`

	// (String) Type of supported action.
	// Available values: "drop", "forward", "worker".
	// Type of matcher.
	// Available values: "all", "literal".
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (List of String)
	// Value for matcher.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type EmailRoutingRuleMatchersObservation struct {

	// (String) Field for type matcher.
	// Available values: "to".
	// Field for type matcher.
	// Available values: "to".
	Field *string `json:"field,omitempty" tf:"field,omitempty"`

	// (String) Type of supported action.
	// Available values: "drop", "forward", "worker".
	// Type of matcher.
	// Available values: "all", "literal".
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (List of String)
	// Value for matcher.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type EmailRoutingRuleMatchersParameters struct {

	// (String) Field for type matcher.
	// Available values: "to".
	// Field for type matcher.
	// Available values: "to".
	// +kubebuilder:validation:Optional
	Field *string `json:"field,omitempty" tf:"field,omitempty"`

	// (String) Type of supported action.
	// Available values: "drop", "forward", "worker".
	// Type of matcher.
	// Available values: "all", "literal".
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`

	// (List of String)
	// Value for matcher.
	// +kubebuilder:validation:Optional
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type EmailRoutingRuleObservation struct {

	// (Attributes List) List actions patterns. (see below for nested schema)
	Actions []EmailRoutingRuleActionsObservation `json:"actions,omitempty" tf:"actions,omitempty"`

	// (Boolean) Routing rule status.
	// Routing rule status.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) Routing rule identifier.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Attributes List) Matching patterns to forward to your actions. (see below for nested schema)
	Matchers []EmailRoutingRuleMatchersObservation `json:"matchers,omitempty" tf:"matchers,omitempty"`

	// (String) Routing rule name.
	// Routing rule name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) Priority of the routing rule.
	// Priority of the routing rule.
	Priority *float64 `json:"priority,omitempty" tf:"priority,omitempty"`

	// (String, Deprecated) Routing rule tag. (Deprecated, replaced by routing rule identifier)
	// Routing rule tag. (Deprecated, replaced by routing rule identifier)
	Tag *string `json:"tag,omitempty" tf:"tag,omitempty"`

	// (String) Identifier.
	// Identifier.
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`
}

type EmailRoutingRuleParameters struct {

	// (Attributes List) List actions patterns. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Actions []EmailRoutingRuleActionsParameters `json:"actions,omitempty" tf:"actions,omitempty"`

	// (Boolean) Routing rule status.
	// Routing rule status.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Attributes List) Matching patterns to forward to your actions. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Matchers []EmailRoutingRuleMatchersParameters `json:"matchers,omitempty" tf:"matchers,omitempty"`

	// (String) Routing rule name.
	// Routing rule name.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) Priority of the routing rule.
	// Priority of the routing rule.
	// +kubebuilder:validation:Optional
	Priority *float64 `json:"priority,omitempty" tf:"priority,omitempty"`

	// (String) Identifier.
	// Identifier.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/zone/v1alpha1.Zone
	// +kubebuilder:validation:Optional
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`

	// Reference to a Zone in zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDRef *v1.NamespacedReference `json:"zoneIdRef,omitempty" tf:"-"`

	// Selector for a Zone in zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDSelector *v1.NamespacedSelector `json:"zoneIdSelector,omitempty" tf:"-"`
}

// EmailRoutingRuleSpec defines the desired state of EmailRoutingRule
type EmailRoutingRuleSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            EmailRoutingRuleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider EmailRoutingRuleInitParameters `json:"initProvider,omitempty"`
}

// EmailRoutingRuleStatus defines the observed state of EmailRoutingRule.
type EmailRoutingRuleStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        EmailRoutingRuleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// EmailRoutingRule is the Schema for the EmailRoutingRules API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,cloudflare}
type EmailRoutingRule struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.actions) || (has(self.initProvider) && has(self.initProvider.actions))",message="spec.forProvider.actions is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.matchers) || (has(self.initProvider) && has(self.initProvider.matchers))",message="spec.forProvider.matchers is a required parameter"
	Spec   EmailRoutingRuleSpec   `json:"spec"`
	Status EmailRoutingRuleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// EmailRoutingRuleList contains a list of EmailRoutingRules
type EmailRoutingRuleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []EmailRoutingRule `json:"items"`
}

// Repository type metadata.
var (
	EmailRoutingRule_Kind             = "EmailRoutingRule"
	EmailRoutingRule_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: EmailRoutingRule_Kind}.String()
	EmailRoutingRule_KindAPIVersion   = EmailRoutingRule_Kind + "." + CRDGroupVersion.String()
	EmailRoutingRule_GroupVersionKind = CRDGroupVersion.WithKind(EmailRoutingRule_Kind)
)

func init() {
	SchemeBuilder.Register(&EmailRoutingRule{}, &EmailRoutingRuleList{})
}
