// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

// Package namespaced contains Kubernetes API for the provider.
package namespaced

import (
	"k8s.io/apimachinery/pkg/runtime"

	v1alpha1 "github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/access/v1alpha1"
	v1alpha1account "github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/account/v1alpha1"
	v1alpha1apishield "github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/apishield/v1alpha1"
	v1alpha1argo "github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/argo/v1alpha1"
	v1alpha1certificate "github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/certificate/v1alpha1"
	v1alpha1dns "github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/dns/v1alpha1"
	v1alpha1email "github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/email/v1alpha1"
	v1alpha1firewall "github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/firewall/v1alpha1"
	v1alpha1healthcheck "github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/healthcheck/v1alpha1"
	v1alpha1list "github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/list/v1alpha1"
	v1alpha1loadbalancer "github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/loadbalancer/v1alpha1"
	v1alpha1logpush "github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/logpush/v1alpha1"
	v1alpha1misc "github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/misc/v1alpha1"
	v1alpha1notification "github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/notification/v1alpha1"
	v1alpha1r2 "github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/r2/v1alpha1"
	v1alpha1spectrum "github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/spectrum/v1alpha1"
	v1alpha1stream "github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/stream/v1alpha1"
	v1alpha1namespaced "github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/v1alpha1"
	v1beta1 "github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/v1beta1"
	v1alpha1waitingroom "github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/waitingroom/v1alpha1"
	v1alpha1workers "github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/workers/v1alpha1"
	v1alpha1zerotrust "github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/zerotrust/v1alpha1"
	v1alpha1zone "github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/zone/v1alpha1"
)

func init() {
	// Register the types with the Scheme so the components can map objects to GroupVersionKinds and back
	AddToSchemes = append(AddToSchemes,
		v1alpha1.SchemeBuilder.AddToScheme,
		v1alpha1account.SchemeBuilder.AddToScheme,
		v1alpha1apishield.SchemeBuilder.AddToScheme,
		v1alpha1argo.SchemeBuilder.AddToScheme,
		v1alpha1certificate.SchemeBuilder.AddToScheme,
		v1alpha1dns.SchemeBuilder.AddToScheme,
		v1alpha1email.SchemeBuilder.AddToScheme,
		v1alpha1firewall.SchemeBuilder.AddToScheme,
		v1alpha1healthcheck.SchemeBuilder.AddToScheme,
		v1alpha1list.SchemeBuilder.AddToScheme,
		v1alpha1loadbalancer.SchemeBuilder.AddToScheme,
		v1alpha1logpush.SchemeBuilder.AddToScheme,
		v1alpha1misc.SchemeBuilder.AddToScheme,
		v1alpha1notification.SchemeBuilder.AddToScheme,
		v1alpha1r2.SchemeBuilder.AddToScheme,
		v1alpha1spectrum.SchemeBuilder.AddToScheme,
		v1alpha1stream.SchemeBuilder.AddToScheme,
		v1alpha1namespaced.SchemeBuilder.AddToScheme,
		v1beta1.SchemeBuilder.AddToScheme,
		v1alpha1waitingroom.SchemeBuilder.AddToScheme,
		v1alpha1workers.SchemeBuilder.AddToScheme,
		v1alpha1zerotrust.SchemeBuilder.AddToScheme,
		v1alpha1zone.SchemeBuilder.AddToScheme,
	)
}

// AddToSchemes may be used to add all resources defined in the project to a Scheme
var AddToSchemes runtime.SchemeBuilder

// AddToScheme adds all Resources to the Scheme
func AddToScheme(s *runtime.Scheme) error {
	return AddToSchemes.AddToScheme(s)
}
