// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type CallsSFUAppInitParameters struct {

	// (String) The account identifier tag.
	// The account identifier tag.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/account/v1alpha1.Account
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// Reference to a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDRef *v1.NamespacedReference `json:"accountIdRef,omitempty" tf:"-"`

	// Selector for a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDSelector *v1.NamespacedSelector `json:"accountIdSelector,omitempty" tf:"-"`

	// generated unique identifier for a item.
	// A Cloudflare-generated unique identifier for a item.
	AppID *string `json:"appId,omitempty" tf:"app_id,omitempty"`

	// (String) A short description of Calls app, not shown to end users.
	// A short description of Calls app, not shown to end users.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type CallsSFUAppObservation struct {

	// (String) The account identifier tag.
	// The account identifier tag.
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// generated unique identifier for a item.
	// A Cloudflare-generated unique identifier for a item.
	AppID *string `json:"appId,omitempty" tf:"app_id,omitempty"`

	// (String) The date and time the item was created.
	// The date and time the item was created.
	Created *string `json:"created,omitempty" tf:"created,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The date and time the item was last modified.
	// The date and time the item was last modified.
	Modified *string `json:"modified,omitempty" tf:"modified,omitempty"`

	// (String) A short description of Calls app, not shown to end users.
	// A short description of Calls app, not shown to end users.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// generated unique identifier for a item.
	// A Cloudflare-generated unique identifier for a item.
	UID *string `json:"uid,omitempty" tf:"uid,omitempty"`
}

type CallsSFUAppParameters struct {

	// (String) The account identifier tag.
	// The account identifier tag.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/account/v1alpha1.Account
	// +kubebuilder:validation:Optional
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// Reference to a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDRef *v1.NamespacedReference `json:"accountIdRef,omitempty" tf:"-"`

	// Selector for a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDSelector *v1.NamespacedSelector `json:"accountIdSelector,omitempty" tf:"-"`

	// generated unique identifier for a item.
	// A Cloudflare-generated unique identifier for a item.
	// +kubebuilder:validation:Optional
	AppID *string `json:"appId,omitempty" tf:"app_id,omitempty"`

	// (String) A short description of Calls app, not shown to end users.
	// A short description of Calls app, not shown to end users.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

// CallsSFUAppSpec defines the desired state of CallsSFUApp
type CallsSFUAppSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            CallsSFUAppParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider CallsSFUAppInitParameters `json:"initProvider,omitempty"`
}

// CallsSFUAppStatus defines the observed state of CallsSFUApp.
type CallsSFUAppStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        CallsSFUAppObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// CallsSFUApp is the Schema for the CallsSFUApps API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,cloudflare}
type CallsSFUApp struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              CallsSFUAppSpec   `json:"spec"`
	Status            CallsSFUAppStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CallsSFUAppList contains a list of CallsSFUApps
type CallsSFUAppList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CallsSFUApp `json:"items"`
}

// Repository type metadata.
var (
	CallsSFUApp_Kind             = "CallsSFUApp"
	CallsSFUApp_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: CallsSFUApp_Kind}.String()
	CallsSFUApp_KindAPIVersion   = CallsSFUApp_Kind + "." + CRDGroupVersion.String()
	CallsSFUApp_GroupVersionKind = CRDGroupVersion.WithKind(CallsSFUApp_Kind)
)

func init() {
	SchemeBuilder.Register(&CallsSFUApp{}, &CallsSFUAppList{})
}
