// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *AddressMap) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BYOIPPrefix) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *CallsSFUApp) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *CallsTURNApp) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *CloudConnectorRules) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *CloudforceOneRequest) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *CloudforceOneRequestAsset) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *CloudforceOneRequestMessage) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *CloudforceOneRequestPriority) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ContentScanning) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ContentScanningExpression) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *D1Database) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *HyperdriveConfig) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ObservatoryScheduledTest) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Queue) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *QueueConsumer) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RegionalHostname) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Snippet) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SnippetRules) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *TurnstileWidget) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Web3Hostname) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *WebAnalyticsRule) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *WebAnalyticsSite) Hub() {}
