// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type RegionalHostnameInitParameters struct {

	// (String) DNS hostname to be regionalized, must be a subdomain of the zone. Wildcards are supported for one level, e.g *.example.com
	// DNS hostname to be regionalized, must be a subdomain of the zone. Wildcards are supported for one level, e.g `*.example.com`
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// (String) Identifying key for the region
	// Identifying key for the region
	RegionKey *string `json:"regionKey,omitempty" tf:"region_key,omitempty"`

	// (String) Configure which routing method to use for the regional hostname
	// Configure which routing method to use for the regional hostname
	Routing *string `json:"routing,omitempty" tf:"routing,omitempty"`

	// (String) Identifier.
	// Identifier.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/zone/v1alpha1.Zone
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`

	// Reference to a Zone in zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDRef *v1.NamespacedReference `json:"zoneIdRef,omitempty" tf:"-"`

	// Selector for a Zone in zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDSelector *v1.NamespacedSelector `json:"zoneIdSelector,omitempty" tf:"-"`
}

type RegionalHostnameObservation struct {

	// (String) When the regional hostname was created
	// When the regional hostname was created
	CreatedOn *string `json:"createdOn,omitempty" tf:"created_on,omitempty"`

	// (String) DNS hostname to be regionalized, must be a subdomain of the zone. Wildcards are supported for one level, e.g *.example.com
	// DNS hostname to be regionalized, must be a subdomain of the zone. Wildcards are supported for one level, e.g `*.example.com`
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// (String) DNS hostname to be regionalized, must be a subdomain of the zone. Wildcards are supported for one level, e.g *.example.com
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Identifying key for the region
	// Identifying key for the region
	RegionKey *string `json:"regionKey,omitempty" tf:"region_key,omitempty"`

	// (String) Configure which routing method to use for the regional hostname
	// Configure which routing method to use for the regional hostname
	Routing *string `json:"routing,omitempty" tf:"routing,omitempty"`

	// (String) Identifier.
	// Identifier.
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`
}

type RegionalHostnameParameters struct {

	// (String) DNS hostname to be regionalized, must be a subdomain of the zone. Wildcards are supported for one level, e.g *.example.com
	// DNS hostname to be regionalized, must be a subdomain of the zone. Wildcards are supported for one level, e.g `*.example.com`
	// +kubebuilder:validation:Optional
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// (String) Identifying key for the region
	// Identifying key for the region
	// +kubebuilder:validation:Optional
	RegionKey *string `json:"regionKey,omitempty" tf:"region_key,omitempty"`

	// (String) Configure which routing method to use for the regional hostname
	// Configure which routing method to use for the regional hostname
	// +kubebuilder:validation:Optional
	Routing *string `json:"routing,omitempty" tf:"routing,omitempty"`

	// (String) Identifier.
	// Identifier.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/zone/v1alpha1.Zone
	// +kubebuilder:validation:Optional
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`

	// Reference to a Zone in zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDRef *v1.NamespacedReference `json:"zoneIdRef,omitempty" tf:"-"`

	// Selector for a Zone in zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDSelector *v1.NamespacedSelector `json:"zoneIdSelector,omitempty" tf:"-"`
}

// RegionalHostnameSpec defines the desired state of RegionalHostname
type RegionalHostnameSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            RegionalHostnameParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RegionalHostnameInitParameters `json:"initProvider,omitempty"`
}

// RegionalHostnameStatus defines the observed state of RegionalHostname.
type RegionalHostnameStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        RegionalHostnameObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// RegionalHostname is the Schema for the RegionalHostnames API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,cloudflare}
type RegionalHostname struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.hostname) || (has(self.initProvider) && has(self.initProvider.hostname))",message="spec.forProvider.hostname is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.regionKey) || (has(self.initProvider) && has(self.initProvider.regionKey))",message="spec.forProvider.regionKey is a required parameter"
	Spec   RegionalHostnameSpec   `json:"spec"`
	Status RegionalHostnameStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RegionalHostnameList contains a list of RegionalHostnames
type RegionalHostnameList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RegionalHostname `json:"items"`
}

// Repository type metadata.
var (
	RegionalHostname_Kind             = "RegionalHostname"
	RegionalHostname_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: RegionalHostname_Kind}.String()
	RegionalHostname_KindAPIVersion   = RegionalHostname_Kind + "." + CRDGroupVersion.String()
	RegionalHostname_GroupVersionKind = CRDGroupVersion.WithKind(RegionalHostname_Kind)
)

func init() {
	SchemeBuilder.Register(&RegionalHostname{}, &RegionalHostnameList{})
}
