// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type DataInitParameters struct {

	// (String) The desired endpoint to test.
	// The desired endpoint to test.
	Host *string `json:"host,omitempty" tf:"host,omitempty"`

	// (String) The type of test.
	// The type of test.
	Kind *string `json:"kind,omitempty" tf:"kind,omitempty"`

	// (String) The HTTP request method type.
	// The HTTP request method type.
	Method *string `json:"method,omitempty" tf:"method,omitempty"`
}

type DataObservation struct {

	// (String) The desired endpoint to test.
	// The desired endpoint to test.
	Host *string `json:"host,omitempty" tf:"host,omitempty"`

	// (String) The type of test.
	// The type of test.
	Kind *string `json:"kind,omitempty" tf:"kind,omitempty"`

	// (String) The HTTP request method type.
	// The HTTP request method type.
	Method *string `json:"method,omitempty" tf:"method,omitempty"`
}

type DataParameters struct {

	// (String) The desired endpoint to test.
	// The desired endpoint to test.
	// +kubebuilder:validation:Optional
	Host *string `json:"host,omitempty" tf:"host,omitempty"`

	// (String) The type of test.
	// The type of test.
	// +kubebuilder:validation:Optional
	Kind *string `json:"kind,omitempty" tf:"kind,omitempty"`

	// (String) The HTTP request method type.
	// The HTTP request method type.
	// +kubebuilder:validation:Optional
	Method *string `json:"method,omitempty" tf:"method,omitempty"`
}

type TargetPoliciesInitParameters struct {

	// (String) The unique identifier for the test.
	// The id of the DEX rule
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type TargetPoliciesObservation struct {

	// (Boolean) Whether the DEX rule is the account default
	// Whether the DEX rule is the account default
	Default *bool `json:"default,omitempty" tf:"default,omitempty"`

	// (String) The unique identifier for the test.
	// The id of the DEX rule
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The name of the DEX test. Must be unique.
	// The name of the DEX rule
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type TargetPoliciesParameters struct {

	// (String) The unique identifier for the test.
	// The id of the DEX rule
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`
}

type ZeroTrustDEXTestInitParameters struct {

	// (String)
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/account/v1alpha1.Account
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// Reference to a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDRef *v1.NamespacedReference `json:"accountIdRef,omitempty" tf:"-"`

	// Selector for a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDSelector *v1.NamespacedSelector `json:"accountIdSelector,omitempty" tf:"-"`

	// (Attributes) The configuration object which contains the details for the WARP client to conduct the test. (see below for nested schema)
	Data *DataInitParameters `json:"data,omitempty" tf:"data,omitempty"`

	// (String) Additional details about the test.
	// Additional details about the test.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean) Determines whether or not the test is active.
	// Determines whether or not the test is active.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) How often the test will run.
	// How often the test will run.
	Interval *string `json:"interval,omitempty" tf:"interval,omitempty"`

	// (String) The name of the DEX test. Must be unique.
	// The name of the DEX test. Must be unique.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes List) DEX rules targeted by this test (see below for nested schema)
	TargetPolicies []TargetPoliciesInitParameters `json:"targetPolicies,omitempty" tf:"target_policies,omitempty"`
}

type ZeroTrustDEXTestObservation struct {

	// (String)
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// (Attributes) The configuration object which contains the details for the WARP client to conduct the test. (see below for nested schema)
	Data *DataObservation `json:"data,omitempty" tf:"data,omitempty"`

	// (String) Additional details about the test.
	// Additional details about the test.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean) Determines whether or not the test is active.
	// Determines whether or not the test is active.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) The unique identifier for the test.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) How often the test will run.
	// How often the test will run.
	Interval *string `json:"interval,omitempty" tf:"interval,omitempty"`

	// (String) The name of the DEX test. Must be unique.
	// The name of the DEX test. Must be unique.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes List) DEX rules targeted by this test (see below for nested schema)
	TargetPolicies []TargetPoliciesObservation `json:"targetPolicies,omitempty" tf:"target_policies,omitempty"`

	// (Boolean)
	Targeted *bool `json:"targeted,omitempty" tf:"targeted,omitempty"`

	// (String) The unique identifier for the test.
	// The unique identifier for the test.
	TestID *string `json:"testId,omitempty" tf:"test_id,omitempty"`
}

type ZeroTrustDEXTestParameters struct {

	// (String)
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/account/v1alpha1.Account
	// +kubebuilder:validation:Optional
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// Reference to a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDRef *v1.NamespacedReference `json:"accountIdRef,omitempty" tf:"-"`

	// Selector for a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDSelector *v1.NamespacedSelector `json:"accountIdSelector,omitempty" tf:"-"`

	// (Attributes) The configuration object which contains the details for the WARP client to conduct the test. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Data *DataParameters `json:"data,omitempty" tf:"data,omitempty"`

	// (String) Additional details about the test.
	// Additional details about the test.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean) Determines whether or not the test is active.
	// Determines whether or not the test is active.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) How often the test will run.
	// How often the test will run.
	// +kubebuilder:validation:Optional
	Interval *string `json:"interval,omitempty" tf:"interval,omitempty"`

	// (String) The name of the DEX test. Must be unique.
	// The name of the DEX test. Must be unique.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes List) DEX rules targeted by this test (see below for nested schema)
	// +kubebuilder:validation:Optional
	TargetPolicies []TargetPoliciesParameters `json:"targetPolicies,omitempty" tf:"target_policies,omitempty"`
}

// ZeroTrustDEXTestSpec defines the desired state of ZeroTrustDEXTest
type ZeroTrustDEXTestSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ZeroTrustDEXTestParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ZeroTrustDEXTestInitParameters `json:"initProvider,omitempty"`
}

// ZeroTrustDEXTestStatus defines the observed state of ZeroTrustDEXTest.
type ZeroTrustDEXTestStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ZeroTrustDEXTestObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ZeroTrustDEXTest is the Schema for the ZeroTrustDEXTests API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,cloudflare}
type ZeroTrustDEXTest struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.data) || (has(self.initProvider) && has(self.initProvider.data))",message="spec.forProvider.data is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.enabled) || (has(self.initProvider) && has(self.initProvider.enabled))",message="spec.forProvider.enabled is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.interval) || (has(self.initProvider) && has(self.initProvider.interval))",message="spec.forProvider.interval is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   ZeroTrustDEXTestSpec   `json:"spec"`
	Status ZeroTrustDEXTestStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ZeroTrustDEXTestList contains a list of ZeroTrustDEXTests
type ZeroTrustDEXTestList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ZeroTrustDEXTest `json:"items"`
}

// Repository type metadata.
var (
	ZeroTrustDEXTest_Kind             = "ZeroTrustDEXTest"
	ZeroTrustDEXTest_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ZeroTrustDEXTest_Kind}.String()
	ZeroTrustDEXTest_KindAPIVersion   = ZeroTrustDEXTest_Kind + "." + CRDGroupVersion.String()
	ZeroTrustDEXTest_GroupVersionKind = CRDGroupVersion.WithKind(ZeroTrustDEXTest_Kind)
)

func init() {
	SchemeBuilder.Register(&ZeroTrustDEXTest{}, &ZeroTrustDEXTestList{})
}
