apiVersion: dns.cloudflare.m.cloudflare.com/v1alpha1
kind: DNSFirewall
metadata:
  annotations:
    meta.upbound.io/example-id: dns/v1alpha1/dnsfirewall
  labels:
    testing.upbound.io/example-name: example_dns_firewall
  name: example-dns-firewall
  namespace: crossplane-system
spec:
  forProvider:
    accountIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    attackMitigation:
      enabled: true
      onlyWhenUpstreamUnhealthy: false
    deprecateAnyRequests: true
    ecsFallback: false
    maximumCacheTtl: 900
    minimumCacheTtl: 60
    name: My Awesome DNS Firewall cluster
    negativeCacheTtl: 900
    ratelimit: 600
    retries: 2
    upstreamIps:
    - 192.0.2.1
    - 198.51.100.1
    - 2001:DB8:100::CF
