apiVersion: dns.cloudflare.m.cloudflare.com/v1alpha1
kind: DNSRecord
metadata:
  annotations:
    meta.upbound.io/example-id: dns/v1alpha1/dnsrecord
  labels:
    testing.upbound.io/example-name: example_dns_record
  name: example-dns-record
  namespace: crossplane-system
spec:
  forProvider:
    comment: Domain verification record
    content: 198.51.100.4
    name: example.com
    proxied: true
    settings:
      ipv4Only: true
      ipv6Only: true
    tags:
    - owner:dns-team
    ttl: 3600
    type: A
    zoneIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
