apiVersion: stream.cloudflare.crossplane.io/v1alpha1
kind: StreamWatermark
metadata:
  annotations:
    meta.upbound.io/example-id: stream/v1alpha1/streamwatermark
  labels:
    testing.upbound.io/example-name: example_stream_watermark
  name: example-stream-watermark
spec:
  forProvider:
    accountIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    file: '@/Users/rchen/Downloads/watermark.png'
    name: Marketing Videos
    opacity: 0.75
    padding: 0.1
    position: center
    scale: 0.1
