// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Stream) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *StreamAudioTrack) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *StreamDownload) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *StreamKey) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *StreamLiveInput) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *StreamWatermark) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *StreamWebhook) Hub() {}
