apiVersion: account.cloudflare.m.cloudflare.com/v1alpha1
kind: APIToken
metadata:
  annotations:
    meta.upbound.io/example-id: account/v1alpha1/apitoken
  labels:
    testing.upbound.io/example-name: example_api_token
  name: example-api-token
  namespace: crossplane-system
spec:
  forProvider:
    condition:
      requestIp:
        in:
        - 123.123.123.0/24
        - 2606:4700::/32
        notIn:
        - 123.123.123.100/24
        - 2606:4700:4700::/48
    expiresOn: "2020-01-01T00:00:00Z"
    name: readonly token
    notBefore: "2018-07-01T05:20:00Z"
    policies:
    - effect: allow
      permissionGroups:
      - id: c8fed203ed3043cba015a93ad1616f1f
        meta:
          key: key
          value: value
      - id: 82e64a83756745bbbb1c9c2701bf816b
        meta:
          key: key
          value: value
      resources:
        foo: string
