// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type CloudforceOneRequestMessageInitParameters struct {

	// (String) Identifier.
	// Identifier.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/cluster/account/v1alpha1.Account
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// Reference to a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDRef *v1.Reference `json:"accountIdRef,omitempty" tf:"-"`

	// Selector for a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDSelector *v1.Selector `json:"accountIdSelector,omitempty" tf:"-"`

	// (String) Content of message.
	// Content of message.
	Content *string `json:"content,omitempty" tf:"content,omitempty"`

	// (String) UUID.
	// UUID.
	RequestID *string `json:"requestId,omitempty" tf:"request_id,omitempty"`
}

type CloudforceOneRequestMessageObservation struct {

	// (String) Identifier.
	// Identifier.
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// (String) Author of message.
	// Author of message.
	Author *string `json:"author,omitempty" tf:"author,omitempty"`

	// (String) Content of message.
	// Content of message.
	Content *string `json:"content,omitempty" tf:"content,omitempty"`

	// (String) Defines the message creation time.
	// Defines the message creation time.
	Created *string `json:"created,omitempty" tf:"created,omitempty"`

	// (Number) Message ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// on request.
	// Whether the message is a follow-on request.
	IsFollowOnRequest *bool `json:"isFollowOnRequest,omitempty" tf:"is_follow_on_request,omitempty"`

	// (String) UUID.
	// UUID.
	RequestID *string `json:"requestId,omitempty" tf:"request_id,omitempty"`

	// (String) Defines the message last updated time.
	// Defines the message last updated time.
	Updated *string `json:"updated,omitempty" tf:"updated,omitempty"`
}

type CloudforceOneRequestMessageParameters struct {

	// (String) Identifier.
	// Identifier.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/cluster/account/v1alpha1.Account
	// +kubebuilder:validation:Optional
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// Reference to a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDRef *v1.Reference `json:"accountIdRef,omitempty" tf:"-"`

	// Selector for a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDSelector *v1.Selector `json:"accountIdSelector,omitempty" tf:"-"`

	// (String) Content of message.
	// Content of message.
	// +kubebuilder:validation:Optional
	Content *string `json:"content,omitempty" tf:"content,omitempty"`

	// (String) UUID.
	// UUID.
	// +kubebuilder:validation:Optional
	RequestID *string `json:"requestId,omitempty" tf:"request_id,omitempty"`
}

// CloudforceOneRequestMessageSpec defines the desired state of CloudforceOneRequestMessage
type CloudforceOneRequestMessageSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     CloudforceOneRequestMessageParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider CloudforceOneRequestMessageInitParameters `json:"initProvider,omitempty"`
}

// CloudforceOneRequestMessageStatus defines the observed state of CloudforceOneRequestMessage.
type CloudforceOneRequestMessageStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        CloudforceOneRequestMessageObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// CloudforceOneRequestMessage is the Schema for the CloudforceOneRequestMessages API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudflare}
type CloudforceOneRequestMessage struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.requestId) || (has(self.initProvider) && has(self.initProvider.requestId))",message="spec.forProvider.requestId is a required parameter"
	Spec   CloudforceOneRequestMessageSpec   `json:"spec"`
	Status CloudforceOneRequestMessageStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CloudforceOneRequestMessageList contains a list of CloudforceOneRequestMessages
type CloudforceOneRequestMessageList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CloudforceOneRequestMessage `json:"items"`
}

// Repository type metadata.
var (
	CloudforceOneRequestMessage_Kind             = "CloudforceOneRequestMessage"
	CloudforceOneRequestMessage_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: CloudforceOneRequestMessage_Kind}.String()
	CloudforceOneRequestMessage_KindAPIVersion   = CloudforceOneRequestMessage_Kind + "." + CRDGroupVersion.String()
	CloudforceOneRequestMessage_GroupVersionKind = CRDGroupVersion.WithKind(CloudforceOneRequestMessage_Kind)
)

func init() {
	SchemeBuilder.Register(&CloudforceOneRequestMessage{}, &CloudforceOneRequestMessageList{})
}
