// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type CallsTURNAppInitParameters struct {

	// (String) The account identifier tag.
	// The account identifier tag.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/cluster/account/v1alpha1.Account
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// Reference to a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDRef *v1.Reference `json:"accountIdRef,omitempty" tf:"-"`

	// Selector for a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDSelector *v1.Selector `json:"accountIdSelector,omitempty" tf:"-"`

	// generated unique identifier for a item.
	// A Cloudflare-generated unique identifier for a item.
	KeyID *string `json:"keyId,omitempty" tf:"key_id,omitempty"`

	// (String) A short description of a TURN key, not shown to end users.
	// A short description of a TURN key, not shown to end users.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type CallsTURNAppObservation struct {

	// (String) The account identifier tag.
	// The account identifier tag.
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// (String) The date and time the item was created.
	// The date and time the item was created.
	Created *string `json:"created,omitempty" tf:"created,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// generated unique identifier for a item.
	// A Cloudflare-generated unique identifier for a item.
	KeyID *string `json:"keyId,omitempty" tf:"key_id,omitempty"`

	// (String) The date and time the item was last modified.
	// The date and time the item was last modified.
	Modified *string `json:"modified,omitempty" tf:"modified,omitempty"`

	// (String) A short description of a TURN key, not shown to end users.
	// A short description of a TURN key, not shown to end users.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// generated unique identifier for a item.
	// A Cloudflare-generated unique identifier for a item.
	UID *string `json:"uid,omitempty" tf:"uid,omitempty"`
}

type CallsTURNAppParameters struct {

	// (String) The account identifier tag.
	// The account identifier tag.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/cluster/account/v1alpha1.Account
	// +kubebuilder:validation:Optional
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// Reference to a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDRef *v1.Reference `json:"accountIdRef,omitempty" tf:"-"`

	// Selector for a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDSelector *v1.Selector `json:"accountIdSelector,omitempty" tf:"-"`

	// generated unique identifier for a item.
	// A Cloudflare-generated unique identifier for a item.
	// +kubebuilder:validation:Optional
	KeyID *string `json:"keyId,omitempty" tf:"key_id,omitempty"`

	// (String) A short description of a TURN key, not shown to end users.
	// A short description of a TURN key, not shown to end users.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

// CallsTURNAppSpec defines the desired state of CallsTURNApp
type CallsTURNAppSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     CallsTURNAppParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider CallsTURNAppInitParameters `json:"initProvider,omitempty"`
}

// CallsTURNAppStatus defines the observed state of CallsTURNApp.
type CallsTURNAppStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        CallsTURNAppObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// CallsTURNApp is the Schema for the CallsTURNApps API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudflare}
type CallsTURNApp struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              CallsTURNAppSpec   `json:"spec"`
	Status            CallsTURNAppStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CallsTURNAppList contains a list of CallsTURNApps
type CallsTURNAppList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CallsTURNApp `json:"items"`
}

// Repository type metadata.
var (
	CallsTURNApp_Kind             = "CallsTURNApp"
	CallsTURNApp_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: CallsTURNApp_Kind}.String()
	CallsTURNApp_KindAPIVersion   = CallsTURNApp_Kind + "." + CRDGroupVersion.String()
	CallsTURNApp_GroupVersionKind = CRDGroupVersion.WithKind(CallsTURNApp_Kind)
)

func init() {
	SchemeBuilder.Register(&CallsTURNApp{}, &CallsTURNAppList{})
}
