// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type Web3HostnameInitParameters struct {

	// (String) Specify an optional description of the hostname.
	// Specify an optional description of the hostname.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Specify the DNSLink value used if the target is ipfs.
	// Specify the DNSLink value used if the target is ipfs.
	Dnslink *string `json:"dnslink,omitempty" tf:"dnslink,omitempty"`

	// (String) Specify the hostname that points to the target gateway via CNAME.
	// Specify the hostname that points to the target gateway via CNAME.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Specify the target gateway of the hostname.
	// Available values: "ethereum", "ipfs", "ipfs_universal_path".
	// Specify the target gateway of the hostname.
	// Available values: "ethereum", "ipfs", "ipfs_universal_path".
	Target *string `json:"target,omitempty" tf:"target,omitempty"`

	// (String) Specify the identifier of the hostname.
	// Specify the identifier of the hostname.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/cluster/zone/v1alpha1.Zone
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`

	// Reference to a Zone in zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDRef *v1.Reference `json:"zoneIdRef,omitempty" tf:"-"`

	// Selector for a Zone in zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDSelector *v1.Selector `json:"zoneIdSelector,omitempty" tf:"-"`
}

type Web3HostnameObservation struct {

	// (String)
	CreatedOn *string `json:"createdOn,omitempty" tf:"created_on,omitempty"`

	// (String) Specify an optional description of the hostname.
	// Specify an optional description of the hostname.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Specify the DNSLink value used if the target is ipfs.
	// Specify the DNSLink value used if the target is ipfs.
	Dnslink *string `json:"dnslink,omitempty" tf:"dnslink,omitempty"`

	// (String) Specify the identifier of the hostname.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String)
	ModifiedOn *string `json:"modifiedOn,omitempty" tf:"modified_on,omitempty"`

	// (String) Specify the hostname that points to the target gateway via CNAME.
	// Specify the hostname that points to the target gateway via CNAME.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Specifies the status of the hostname's activation.
	// Available values: "active", "pending", "deleting", "error".
	// Specifies the status of the hostname's activation.
	// Available values: "active", "pending", "deleting", "error".
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// (String) Specify the target gateway of the hostname.
	// Available values: "ethereum", "ipfs", "ipfs_universal_path".
	// Specify the target gateway of the hostname.
	// Available values: "ethereum", "ipfs", "ipfs_universal_path".
	Target *string `json:"target,omitempty" tf:"target,omitempty"`

	// (String) Specify the identifier of the hostname.
	// Specify the identifier of the hostname.
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`
}

type Web3HostnameParameters struct {

	// (String) Specify an optional description of the hostname.
	// Specify an optional description of the hostname.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Specify the DNSLink value used if the target is ipfs.
	// Specify the DNSLink value used if the target is ipfs.
	// +kubebuilder:validation:Optional
	Dnslink *string `json:"dnslink,omitempty" tf:"dnslink,omitempty"`

	// (String) Specify the hostname that points to the target gateway via CNAME.
	// Specify the hostname that points to the target gateway via CNAME.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Specify the target gateway of the hostname.
	// Available values: "ethereum", "ipfs", "ipfs_universal_path".
	// Specify the target gateway of the hostname.
	// Available values: "ethereum", "ipfs", "ipfs_universal_path".
	// +kubebuilder:validation:Optional
	Target *string `json:"target,omitempty" tf:"target,omitempty"`

	// (String) Specify the identifier of the hostname.
	// Specify the identifier of the hostname.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/cluster/zone/v1alpha1.Zone
	// +kubebuilder:validation:Optional
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`

	// Reference to a Zone in zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDRef *v1.Reference `json:"zoneIdRef,omitempty" tf:"-"`

	// Selector for a Zone in zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDSelector *v1.Selector `json:"zoneIdSelector,omitempty" tf:"-"`
}

// Web3HostnameSpec defines the desired state of Web3Hostname
type Web3HostnameSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     Web3HostnameParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider Web3HostnameInitParameters `json:"initProvider,omitempty"`
}

// Web3HostnameStatus defines the observed state of Web3Hostname.
type Web3HostnameStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        Web3HostnameObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Web3Hostname is the Schema for the Web3Hostnames API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudflare}
type Web3Hostname struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.target) || (has(self.initProvider) && has(self.initProvider.target))",message="spec.forProvider.target is a required parameter"
	Spec   Web3HostnameSpec   `json:"spec"`
	Status Web3HostnameStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// Web3HostnameList contains a list of Web3Hostnames
type Web3HostnameList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Web3Hostname `json:"items"`
}

// Repository type metadata.
var (
	Web3Hostname_Kind             = "Web3Hostname"
	Web3Hostname_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Web3Hostname_Kind}.String()
	Web3Hostname_KindAPIVersion   = Web3Hostname_Kind + "." + CRDGroupVersion.String()
	Web3Hostname_GroupVersionKind = CRDGroupVersion.WithKind(Web3Hostname_Kind)
)

func init() {
	SchemeBuilder.Register(&Web3Hostname{}, &Web3HostnameList{})
}
