apiVersion: zerotrust.cloudflare.m.cloudflare.com/v1alpha1
kind: ZeroTrustGatewayPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: zerotrust/v1alpha1/zerotrustgatewaypolicy
  labels:
    testing.upbound.io/example-name: example_zero_trust_gateway_policy
  name: example-zero-trust-gateway-policy
  namespace: crossplane-system
spec:
  forProvider:
    accountIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    action: allow
    description: Block bad websites based on their host name.
    devicePosture: any(device_posture.checks.passed[*] in {"1308749e-fcfb-4ebc-b051-fe022b632644"})
    enabled: true
    expiration:
      duration: 10
      expiresAt: "2014-01-01T05:20:20Z"
    filters:
    - http
    identity: any(identity.groups.name[*] in {"finance"})
    name: block bad websites
    precedence: 0
    ruleSettings:
      addHeaders:
        My-Next-Header:
        - foo
        - bar
        X-Custom-Header-Name:
        - somecustomvalue
      allowChildBypass: false
      auditSsh:
        commandLogging: false
      bisoAdminControls:
        copy: remote_only
        dcp: true
        dd: true
        dk: true
        download: enabled
        dp: false
        du: true
        keyboard: enabled
        paste: enabled
        printing: enabled
        upload: enabled
        version: v1
      blockPage:
        includeContext: true
        targetUri: https://example.com
      blockPageEnabled: true
      blockReason: This website is a security risk
      bypassParentRule: false
      checkSession:
        duration: 300s
        enforce: true
      dnsResolvers:
        ipv4:
        - ip: 2.2.2.2
          port: 5053
          routeThroughPrivateNetwork: true
          vnetId: f174e90a-fafe-4643-bbbc-4a0ed4fc8415
        ipv6:
        - ip: '2001:DB8::'
          port: 5053
          routeThroughPrivateNetwork: true
          vnetId: f174e90a-fafe-4643-bbbc-4a0ed4fc8415
      egress:
        ipv4: 192.0.2.2
        ipv4Fallback: 192.0.2.3
        ipv6: 2001:DB8::/64
      forensicCopy:
        enabled: true
      ignoreCnameCategoryMatches: true
      insecureDisableDnssecValidation: false
      ipCategories: true
      ipIndicatorFeeds: true
      l4override:
        ip: 1.1.1.1
        port: 0
      notificationSettings:
        enabled: true
        includeContext: true
        msg: msg
        supportUrl: support_url
      overrideHost: example.com
      overrideIps:
      - 1.1.1.1
      - 2.2.2.2
      payloadLog:
        enabled: true
      quarantine:
        fileTypes:
        - exe
      redirect:
        includeContext: true
        preservePathAndQuery: true
        targetUri: https://example.com
      resolveDnsInternally:
        fallback: none
        viewId: view_id
      resolveDnsThroughCloudflare: true
      untrustedCert:
        action: error
    schedule:
      fri: 08:00-12:30,13:30-17:00
      mon: 08:00-12:30,13:30-17:00
      sat: 08:00-12:30,13:30-17:00
      sun: 08:00-12:30,13:30-17:00
      thu: 08:00-12:30,13:30-17:00
      timeZone: America/New York
      tue: 08:00-12:30,13:30-17:00
      wed: 08:00-12:30,13:30-17:00
    traffic: http.request.uri matches ".*a/partial/uri.*" and http.request.host in
      $01302951-49f9-47c9-a400-0297e60b6a10
