apiVersion: zerotrust.cloudflare.m.cloudflare.com/v1alpha1
kind: ZeroTrustDevicePostureRule
metadata:
  annotations:
    meta.upbound.io/example-id: zerotrust/v1alpha1/zerotrustdeviceposturerule
  labels:
    testing.upbound.io/example-name: example_zero_trust_device_posture_rule
  name: example-zero-trust-device-posture-rule
  namespace: crossplane-system
spec:
  forProvider:
    accountIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    description: The rule for admin serial numbers
    expiration: 1h
    input:
      exists: true
      operatingSystem: linux
      path: /bin/cat
      sha256: https://api.us-2.crowdstrike.com
      thumbprint: 0aabab210bdb998e9cf45da2c9ce352977ab531c681b74cf1e487be1bbe9fe6e
    match:
    - platform: windows
    name: Admin Serial Numbers
    schedule: 1h
    type: file
