apiVersion: zerotrust.cloudflare.m.cloudflare.com/v1alpha1
kind: ZeroTrustDLPCustomProfile
metadata:
  annotations:
    meta.upbound.io/example-id: zerotrust/v1alpha1/zerotrustdlpcustomprofile
  labels:
    testing.upbound.io/example-name: example_zero_trust_dlp_custom_profile
  name: example-zero-trust-dlp-custom-profile
  namespace: crossplane-system
spec:
  forProvider:
    accountIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    aiContextEnabled: true
    allowedMatchCount: 5
    confidenceThreshold: confidence_threshold
    contextAwareness:
      enabled: true
      skip:
        files: true
    description: description
    name: name
    ocrEnabled: true
    sharedEntries:
    - enabled: true
      entryId: 182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e
      entryType: custom
