apiVersion: r2.cloudflare.crossplane.io/v1alpha1
kind: R2BucketCORS
metadata:
  annotations:
    meta.upbound.io/example-id: r2/v1alpha1/r2bucketcors
  labels:
    testing.upbound.io/example-name: example_r2_bucket_cors
  name: example-r2-bucket-cors
spec:
  forProvider:
    accountIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    bucketNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    rules:
    - allowed:
        headers:
        - x-requested-by
        methods:
        - GET
        origins:
        - http://localhost:3000
      exposeHeaders:
      - Content-Encoding
      id: Allow Local Development
      maxAgeSeconds: 3600
