apiVersion: misc.cloudflare.m.cloudflare.com/v1alpha1
kind: WebAnalyticsRule
metadata:
  annotations:
    meta.upbound.io/example-id: misc/v1alpha1/webanalyticsrule
  labels:
    testing.upbound.io/example-name: example_web_analytics_rule
  name: example-web-analytics-rule
  namespace: crossplane-system
spec:
  forProvider:
    accountIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    host: example.com
    inclusive: true
    isPaused: false
    paths:
    - '*'
    rulesetId: f174e90a-fafe-4643-bbbc-4a0ed4fc8415
