apiVersion: access.cloudflare.m.cloudflare.com/v1alpha1
kind: AccessRule
metadata:
  annotations:
    meta.upbound.io/example-id: access/v1alpha1/accessrule
  labels:
    testing.upbound.io/example-name: example_access_rule
  name: example-access-rule
  namespace: crossplane-system
spec:
  forProvider:
    configuration:
      target: ip
      value: 198.51.100.4
    mode: challenge
    notes: This rule is enabled because of an event that occurred on date X.
    zoneIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
