//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogpullRetention) DeepCopyInto(out *LogpullRetention) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogpullRetention.
func (in *LogpullRetention) DeepCopy() *LogpullRetention {
	if in == nil {
		return nil
	}
	out := new(LogpullRetention)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LogpullRetention) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogpullRetentionInitParameters) DeepCopyInto(out *LogpullRetentionInitParameters) {
	*out = *in
	if in.Flag != nil {
		in, out := &in.Flag, &out.Flag
		*out = new(bool)
		**out = **in
	}
	if in.ZoneID != nil {
		in, out := &in.ZoneID, &out.ZoneID
		*out = new(string)
		**out = **in
	}
	if in.ZoneIDRef != nil {
		in, out := &in.ZoneIDRef, &out.ZoneIDRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.ZoneIDSelector != nil {
		in, out := &in.ZoneIDSelector, &out.ZoneIDSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogpullRetentionInitParameters.
func (in *LogpullRetentionInitParameters) DeepCopy() *LogpullRetentionInitParameters {
	if in == nil {
		return nil
	}
	out := new(LogpullRetentionInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogpullRetentionList) DeepCopyInto(out *LogpullRetentionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LogpullRetention, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogpullRetentionList.
func (in *LogpullRetentionList) DeepCopy() *LogpullRetentionList {
	if in == nil {
		return nil
	}
	out := new(LogpullRetentionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LogpullRetentionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogpullRetentionObservation) DeepCopyInto(out *LogpullRetentionObservation) {
	*out = *in
	if in.Flag != nil {
		in, out := &in.Flag, &out.Flag
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.ZoneID != nil {
		in, out := &in.ZoneID, &out.ZoneID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogpullRetentionObservation.
func (in *LogpullRetentionObservation) DeepCopy() *LogpullRetentionObservation {
	if in == nil {
		return nil
	}
	out := new(LogpullRetentionObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogpullRetentionParameters) DeepCopyInto(out *LogpullRetentionParameters) {
	*out = *in
	if in.Flag != nil {
		in, out := &in.Flag, &out.Flag
		*out = new(bool)
		**out = **in
	}
	if in.ZoneID != nil {
		in, out := &in.ZoneID, &out.ZoneID
		*out = new(string)
		**out = **in
	}
	if in.ZoneIDRef != nil {
		in, out := &in.ZoneIDRef, &out.ZoneIDRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.ZoneIDSelector != nil {
		in, out := &in.ZoneIDSelector, &out.ZoneIDSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogpullRetentionParameters.
func (in *LogpullRetentionParameters) DeepCopy() *LogpullRetentionParameters {
	if in == nil {
		return nil
	}
	out := new(LogpullRetentionParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogpullRetentionSpec) DeepCopyInto(out *LogpullRetentionSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogpullRetentionSpec.
func (in *LogpullRetentionSpec) DeepCopy() *LogpullRetentionSpec {
	if in == nil {
		return nil
	}
	out := new(LogpullRetentionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogpullRetentionStatus) DeepCopyInto(out *LogpullRetentionStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogpullRetentionStatus.
func (in *LogpullRetentionStatus) DeepCopy() *LogpullRetentionStatus {
	if in == nil {
		return nil
	}
	out := new(LogpullRetentionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogpushJob) DeepCopyInto(out *LogpushJob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogpushJob.
func (in *LogpushJob) DeepCopy() *LogpushJob {
	if in == nil {
		return nil
	}
	out := new(LogpushJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LogpushJob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogpushJobInitParameters) DeepCopyInto(out *LogpushJobInitParameters) {
	*out = *in
	if in.AccountID != nil {
		in, out := &in.AccountID, &out.AccountID
		*out = new(string)
		**out = **in
	}
	if in.AccountIDRef != nil {
		in, out := &in.AccountIDRef, &out.AccountIDRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.AccountIDSelector != nil {
		in, out := &in.AccountIDSelector, &out.AccountIDSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Dataset != nil {
		in, out := &in.Dataset, &out.Dataset
		*out = new(string)
		**out = **in
	}
	if in.DestinationConf != nil {
		in, out := &in.DestinationConf, &out.DestinationConf
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Filter != nil {
		in, out := &in.Filter, &out.Filter
		*out = new(string)
		**out = **in
	}
	if in.Frequency != nil {
		in, out := &in.Frequency, &out.Frequency
		*out = new(string)
		**out = **in
	}
	if in.Kind != nil {
		in, out := &in.Kind, &out.Kind
		*out = new(string)
		**out = **in
	}
	if in.LogpullOptions != nil {
		in, out := &in.LogpullOptions, &out.LogpullOptions
		*out = new(string)
		**out = **in
	}
	if in.MaxUploadBytes != nil {
		in, out := &in.MaxUploadBytes, &out.MaxUploadBytes
		*out = new(float64)
		**out = **in
	}
	if in.MaxUploadIntervalSeconds != nil {
		in, out := &in.MaxUploadIntervalSeconds, &out.MaxUploadIntervalSeconds
		*out = new(float64)
		**out = **in
	}
	if in.MaxUploadRecords != nil {
		in, out := &in.MaxUploadRecords, &out.MaxUploadRecords
		*out = new(float64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OutputOptions != nil {
		in, out := &in.OutputOptions, &out.OutputOptions
		*out = new(OutputOptionsInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.OwnershipChallengeSecretRef != nil {
		in, out := &in.OwnershipChallengeSecretRef, &out.OwnershipChallengeSecretRef
		*out = new(v1.LocalSecretKeySelector)
		**out = **in
	}
	if in.ZoneID != nil {
		in, out := &in.ZoneID, &out.ZoneID
		*out = new(string)
		**out = **in
	}
	if in.ZoneIDRef != nil {
		in, out := &in.ZoneIDRef, &out.ZoneIDRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.ZoneIDSelector != nil {
		in, out := &in.ZoneIDSelector, &out.ZoneIDSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogpushJobInitParameters.
func (in *LogpushJobInitParameters) DeepCopy() *LogpushJobInitParameters {
	if in == nil {
		return nil
	}
	out := new(LogpushJobInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogpushJobList) DeepCopyInto(out *LogpushJobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LogpushJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogpushJobList.
func (in *LogpushJobList) DeepCopy() *LogpushJobList {
	if in == nil {
		return nil
	}
	out := new(LogpushJobList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LogpushJobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogpushJobObservation) DeepCopyInto(out *LogpushJobObservation) {
	*out = *in
	if in.AccountID != nil {
		in, out := &in.AccountID, &out.AccountID
		*out = new(string)
		**out = **in
	}
	if in.Dataset != nil {
		in, out := &in.Dataset, &out.Dataset
		*out = new(string)
		**out = **in
	}
	if in.DestinationConf != nil {
		in, out := &in.DestinationConf, &out.DestinationConf
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ErrorMessage != nil {
		in, out := &in.ErrorMessage, &out.ErrorMessage
		*out = new(string)
		**out = **in
	}
	if in.Filter != nil {
		in, out := &in.Filter, &out.Filter
		*out = new(string)
		**out = **in
	}
	if in.Frequency != nil {
		in, out := &in.Frequency, &out.Frequency
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Kind != nil {
		in, out := &in.Kind, &out.Kind
		*out = new(string)
		**out = **in
	}
	if in.LastComplete != nil {
		in, out := &in.LastComplete, &out.LastComplete
		*out = new(string)
		**out = **in
	}
	if in.LastError != nil {
		in, out := &in.LastError, &out.LastError
		*out = new(string)
		**out = **in
	}
	if in.LogpullOptions != nil {
		in, out := &in.LogpullOptions, &out.LogpullOptions
		*out = new(string)
		**out = **in
	}
	if in.MaxUploadBytes != nil {
		in, out := &in.MaxUploadBytes, &out.MaxUploadBytes
		*out = new(float64)
		**out = **in
	}
	if in.MaxUploadIntervalSeconds != nil {
		in, out := &in.MaxUploadIntervalSeconds, &out.MaxUploadIntervalSeconds
		*out = new(float64)
		**out = **in
	}
	if in.MaxUploadRecords != nil {
		in, out := &in.MaxUploadRecords, &out.MaxUploadRecords
		*out = new(float64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OutputOptions != nil {
		in, out := &in.OutputOptions, &out.OutputOptions
		*out = new(OutputOptionsObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.ZoneID != nil {
		in, out := &in.ZoneID, &out.ZoneID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogpushJobObservation.
func (in *LogpushJobObservation) DeepCopy() *LogpushJobObservation {
	if in == nil {
		return nil
	}
	out := new(LogpushJobObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogpushJobParameters) DeepCopyInto(out *LogpushJobParameters) {
	*out = *in
	if in.AccountID != nil {
		in, out := &in.AccountID, &out.AccountID
		*out = new(string)
		**out = **in
	}
	if in.AccountIDRef != nil {
		in, out := &in.AccountIDRef, &out.AccountIDRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.AccountIDSelector != nil {
		in, out := &in.AccountIDSelector, &out.AccountIDSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Dataset != nil {
		in, out := &in.Dataset, &out.Dataset
		*out = new(string)
		**out = **in
	}
	if in.DestinationConf != nil {
		in, out := &in.DestinationConf, &out.DestinationConf
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Filter != nil {
		in, out := &in.Filter, &out.Filter
		*out = new(string)
		**out = **in
	}
	if in.Frequency != nil {
		in, out := &in.Frequency, &out.Frequency
		*out = new(string)
		**out = **in
	}
	if in.Kind != nil {
		in, out := &in.Kind, &out.Kind
		*out = new(string)
		**out = **in
	}
	if in.LogpullOptions != nil {
		in, out := &in.LogpullOptions, &out.LogpullOptions
		*out = new(string)
		**out = **in
	}
	if in.MaxUploadBytes != nil {
		in, out := &in.MaxUploadBytes, &out.MaxUploadBytes
		*out = new(float64)
		**out = **in
	}
	if in.MaxUploadIntervalSeconds != nil {
		in, out := &in.MaxUploadIntervalSeconds, &out.MaxUploadIntervalSeconds
		*out = new(float64)
		**out = **in
	}
	if in.MaxUploadRecords != nil {
		in, out := &in.MaxUploadRecords, &out.MaxUploadRecords
		*out = new(float64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OutputOptions != nil {
		in, out := &in.OutputOptions, &out.OutputOptions
		*out = new(OutputOptionsParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.OwnershipChallengeSecretRef != nil {
		in, out := &in.OwnershipChallengeSecretRef, &out.OwnershipChallengeSecretRef
		*out = new(v1.LocalSecretKeySelector)
		**out = **in
	}
	if in.ZoneID != nil {
		in, out := &in.ZoneID, &out.ZoneID
		*out = new(string)
		**out = **in
	}
	if in.ZoneIDRef != nil {
		in, out := &in.ZoneIDRef, &out.ZoneIDRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.ZoneIDSelector != nil {
		in, out := &in.ZoneIDSelector, &out.ZoneIDSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogpushJobParameters.
func (in *LogpushJobParameters) DeepCopy() *LogpushJobParameters {
	if in == nil {
		return nil
	}
	out := new(LogpushJobParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogpushJobSpec) DeepCopyInto(out *LogpushJobSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogpushJobSpec.
func (in *LogpushJobSpec) DeepCopy() *LogpushJobSpec {
	if in == nil {
		return nil
	}
	out := new(LogpushJobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogpushJobStatus) DeepCopyInto(out *LogpushJobStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogpushJobStatus.
func (in *LogpushJobStatus) DeepCopy() *LogpushJobStatus {
	if in == nil {
		return nil
	}
	out := new(LogpushJobStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutputOptionsInitParameters) DeepCopyInto(out *OutputOptionsInitParameters) {
	*out = *in
	if in.BatchPrefix != nil {
		in, out := &in.BatchPrefix, &out.BatchPrefix
		*out = new(string)
		**out = **in
	}
	if in.BatchSuffix != nil {
		in, out := &in.BatchSuffix, &out.BatchSuffix
		*out = new(string)
		**out = **in
	}
	if in.Cve202144228 != nil {
		in, out := &in.Cve202144228, &out.Cve202144228
		*out = new(bool)
		**out = **in
	}
	if in.FieldDelimiter != nil {
		in, out := &in.FieldDelimiter, &out.FieldDelimiter
		*out = new(string)
		**out = **in
	}
	if in.FieldNames != nil {
		in, out := &in.FieldNames, &out.FieldNames
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.OutputType != nil {
		in, out := &in.OutputType, &out.OutputType
		*out = new(string)
		**out = **in
	}
	if in.RecordDelimiter != nil {
		in, out := &in.RecordDelimiter, &out.RecordDelimiter
		*out = new(string)
		**out = **in
	}
	if in.RecordPrefix != nil {
		in, out := &in.RecordPrefix, &out.RecordPrefix
		*out = new(string)
		**out = **in
	}
	if in.RecordSuffix != nil {
		in, out := &in.RecordSuffix, &out.RecordSuffix
		*out = new(string)
		**out = **in
	}
	if in.RecordTemplate != nil {
		in, out := &in.RecordTemplate, &out.RecordTemplate
		*out = new(string)
		**out = **in
	}
	if in.SampleRate != nil {
		in, out := &in.SampleRate, &out.SampleRate
		*out = new(float64)
		**out = **in
	}
	if in.TimestampFormat != nil {
		in, out := &in.TimestampFormat, &out.TimestampFormat
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutputOptionsInitParameters.
func (in *OutputOptionsInitParameters) DeepCopy() *OutputOptionsInitParameters {
	if in == nil {
		return nil
	}
	out := new(OutputOptionsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutputOptionsObservation) DeepCopyInto(out *OutputOptionsObservation) {
	*out = *in
	if in.BatchPrefix != nil {
		in, out := &in.BatchPrefix, &out.BatchPrefix
		*out = new(string)
		**out = **in
	}
	if in.BatchSuffix != nil {
		in, out := &in.BatchSuffix, &out.BatchSuffix
		*out = new(string)
		**out = **in
	}
	if in.Cve202144228 != nil {
		in, out := &in.Cve202144228, &out.Cve202144228
		*out = new(bool)
		**out = **in
	}
	if in.FieldDelimiter != nil {
		in, out := &in.FieldDelimiter, &out.FieldDelimiter
		*out = new(string)
		**out = **in
	}
	if in.FieldNames != nil {
		in, out := &in.FieldNames, &out.FieldNames
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.OutputType != nil {
		in, out := &in.OutputType, &out.OutputType
		*out = new(string)
		**out = **in
	}
	if in.RecordDelimiter != nil {
		in, out := &in.RecordDelimiter, &out.RecordDelimiter
		*out = new(string)
		**out = **in
	}
	if in.RecordPrefix != nil {
		in, out := &in.RecordPrefix, &out.RecordPrefix
		*out = new(string)
		**out = **in
	}
	if in.RecordSuffix != nil {
		in, out := &in.RecordSuffix, &out.RecordSuffix
		*out = new(string)
		**out = **in
	}
	if in.RecordTemplate != nil {
		in, out := &in.RecordTemplate, &out.RecordTemplate
		*out = new(string)
		**out = **in
	}
	if in.SampleRate != nil {
		in, out := &in.SampleRate, &out.SampleRate
		*out = new(float64)
		**out = **in
	}
	if in.TimestampFormat != nil {
		in, out := &in.TimestampFormat, &out.TimestampFormat
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutputOptionsObservation.
func (in *OutputOptionsObservation) DeepCopy() *OutputOptionsObservation {
	if in == nil {
		return nil
	}
	out := new(OutputOptionsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutputOptionsParameters) DeepCopyInto(out *OutputOptionsParameters) {
	*out = *in
	if in.BatchPrefix != nil {
		in, out := &in.BatchPrefix, &out.BatchPrefix
		*out = new(string)
		**out = **in
	}
	if in.BatchSuffix != nil {
		in, out := &in.BatchSuffix, &out.BatchSuffix
		*out = new(string)
		**out = **in
	}
	if in.Cve202144228 != nil {
		in, out := &in.Cve202144228, &out.Cve202144228
		*out = new(bool)
		**out = **in
	}
	if in.FieldDelimiter != nil {
		in, out := &in.FieldDelimiter, &out.FieldDelimiter
		*out = new(string)
		**out = **in
	}
	if in.FieldNames != nil {
		in, out := &in.FieldNames, &out.FieldNames
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.OutputType != nil {
		in, out := &in.OutputType, &out.OutputType
		*out = new(string)
		**out = **in
	}
	if in.RecordDelimiter != nil {
		in, out := &in.RecordDelimiter, &out.RecordDelimiter
		*out = new(string)
		**out = **in
	}
	if in.RecordPrefix != nil {
		in, out := &in.RecordPrefix, &out.RecordPrefix
		*out = new(string)
		**out = **in
	}
	if in.RecordSuffix != nil {
		in, out := &in.RecordSuffix, &out.RecordSuffix
		*out = new(string)
		**out = **in
	}
	if in.RecordTemplate != nil {
		in, out := &in.RecordTemplate, &out.RecordTemplate
		*out = new(string)
		**out = **in
	}
	if in.SampleRate != nil {
		in, out := &in.SampleRate, &out.SampleRate
		*out = new(float64)
		**out = **in
	}
	if in.TimestampFormat != nil {
		in, out := &in.TimestampFormat, &out.TimestampFormat
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutputOptionsParameters.
func (in *OutputOptionsParameters) DeepCopy() *OutputOptionsParameters {
	if in == nil {
		return nil
	}
	out := new(OutputOptionsParameters)
	in.DeepCopyInto(out)
	return out
}
