// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type LogpullRetentionInitParameters struct {

	// (Boolean) The log retention flag for Logpull API.
	// The log retention flag for Logpull API.
	Flag *bool `json:"flag,omitempty" tf:"flag,omitempty"`

	// (String) Identifier.
	// Identifier.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/zone/v1alpha1.Zone
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`

	// Reference to a Zone in zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDRef *v1.NamespacedReference `json:"zoneIdRef,omitempty" tf:"-"`

	// Selector for a Zone in zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDSelector *v1.NamespacedSelector `json:"zoneIdSelector,omitempty" tf:"-"`
}

type LogpullRetentionObservation struct {

	// (Boolean) The log retention flag for Logpull API.
	// The log retention flag for Logpull API.
	Flag *bool `json:"flag,omitempty" tf:"flag,omitempty"`

	// (String) Identifier.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Identifier.
	// Identifier.
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`
}

type LogpullRetentionParameters struct {

	// (Boolean) The log retention flag for Logpull API.
	// The log retention flag for Logpull API.
	// +kubebuilder:validation:Optional
	Flag *bool `json:"flag,omitempty" tf:"flag,omitempty"`

	// (String) Identifier.
	// Identifier.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/zone/v1alpha1.Zone
	// +kubebuilder:validation:Optional
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`

	// Reference to a Zone in zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDRef *v1.NamespacedReference `json:"zoneIdRef,omitempty" tf:"-"`

	// Selector for a Zone in zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDSelector *v1.NamespacedSelector `json:"zoneIdSelector,omitempty" tf:"-"`
}

// LogpullRetentionSpec defines the desired state of LogpullRetention
type LogpullRetentionSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            LogpullRetentionParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider LogpullRetentionInitParameters `json:"initProvider,omitempty"`
}

// LogpullRetentionStatus defines the observed state of LogpullRetention.
type LogpullRetentionStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        LogpullRetentionObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// LogpullRetention is the Schema for the LogpullRetentions API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,cloudflare}
type LogpullRetention struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              LogpullRetentionSpec   `json:"spec"`
	Status            LogpullRetentionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// LogpullRetentionList contains a list of LogpullRetentions
type LogpullRetentionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []LogpullRetention `json:"items"`
}

// Repository type metadata.
var (
	LogpullRetention_Kind             = "LogpullRetention"
	LogpullRetention_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: LogpullRetention_Kind}.String()
	LogpullRetention_KindAPIVersion   = LogpullRetention_Kind + "." + CRDGroupVersion.String()
	LogpullRetention_GroupVersionKind = CRDGroupVersion.WithKind(LogpullRetention_Kind)
)

func init() {
	SchemeBuilder.Register(&LogpullRetention{}, &LogpullRetentionList{})
}
