apiVersion: zone.cloudflare.crossplane.io/v1alpha1
kind: ZoneDNSSEC
metadata:
  annotations:
    meta.upbound.io/example-id: zone/v1alpha1/zonednssec
  labels:
    testing.upbound.io/example-name: example_zone_dnssec
  name: example-zone-dnssec
spec:
  forProvider:
    dnssecMultiSigner: false
    dnssecPresigned: true
    dnssecUseNsec3: false
    status: active
    zoneIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
