apiVersion: firewall.cloudflare.crossplane.io/v1alpha1
kind: FirewallRule
metadata:
  annotations:
    meta.upbound.io/example-id: firewall/v1alpha1/firewallrule
  labels:
    testing.upbound.io/example-name: example_firewall_rule
  name: example-firewall-rule
spec:
  forProvider:
    action:
      mode: challenge
      response:
        body: <error>This request has been rate-limited.</error>
        contentType: text/xml
      timeout: 86400
    filter:
      description: Restrict access from these browsers on this address range.
      expression: (http.request.uri.path ~ ".*wp-login.php" or http.request.uri.path
        ~ ".*xmlrpc.php") and ip.addr ne 172.16.22.155
      paused: false
      ref: FIL-100
    zoneIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
