apiVersion: firewall.cloudflare.crossplane.io/v1alpha1
kind: LeakedCredentialCheckRule
metadata:
  annotations:
    meta.upbound.io/example-id: firewall/v1alpha1/leakedcredentialcheckrule
  labels:
    testing.upbound.io/example-name: example_leaked_credential_check_rule
  name: example-leaked-credential-check-rule
spec:
  forProvider:
    password: lookup_json_string(http.request.body.raw, "secret")
    username: lookup_json_string(http.request.body.raw, "user")
    zoneIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
