apiVersion: r2.cloudflare.m.cloudflare.com/v1alpha1
kind: R2BucketLifecycle
metadata:
  annotations:
    meta.upbound.io/example-id: r2/v1alpha1/r2bucketlifecycle
  labels:
    testing.upbound.io/example-name: example_r2_bucket_lifecycle
  name: example-r2-bucket-lifecycle
  namespace: crossplane-system
spec:
  forProvider:
    accountIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    bucketNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    rules:
    - abortMultipartUploadsTransition:
        condition:
          maxAge: 0
          type: Age
      conditions:
        prefix: prefix
      deleteObjectsTransition:
        condition:
          maxAge: 0
          type: Age
      enabled: true
      id: Expire all objects older than 24 hours
      storageClassTransitions:
      - condition:
          maxAge: 0
          type: Age
        storageClass: InfrequentAccess
